### ISSUE TITLE
Controlling what features should be enabled

### ISSUE THREAD

**Issue by lilliesAndRoses** [davidhalter/jedi-vim#924] opened 2019-03-28 04:19 UTC
This is not an issue, but a question. 
I want to use Jedi for a restricted editor where I want only select keywords to be allowed.
As an example, I do not want to support lambdas or closures.
Can I exclude this through any setting or do I need to tweak some code to achieve this?
Another use case is can I configure Jedi to allow only Python 2.7 builtins?

**Comment by davidhalter** [comment] 2019-04-05 12:49
Exact duplicate of #1303.

**Closed by davidhalter** 2019-04-05 12:49 UTC
