### ISSUE TITLE
Latest update breaks Neovim capability for goto function assignments & definitions?

### ISSUE THREAD

**Issue by perks** [davidhalter/jedi-vim#482] opened 2015-10-19 21:40 UTC
Recently updated the plugin, and found this error being fired off when trying to take advantage of the ```<leader> g``` and ```<leader> d``` behaviour.

Python installed correctly (```echo has("python")```) as well as running ```:JediDebugInfo``` returns: ```Using Python version: 2```

The error mentions something about tags, I've never generated tags before for this project and it was working flawlessly before

Bellow is traceback: 

```
Traceback (most recent call last):
  File "/home/chris/.vim/plugged/jedi-vim/jedi_vim.py", line 119, in wrapper
    return func(*args, **kwargs)
  File "/home/chris/.vim/plugged/jedi-vim/jedi_vim.py", line 267, in goto
    vim.command('tjump %s' % tagname)
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/nvim.py", line 119, in command
    return self._session.request('vim_command', string, async=async)
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/common.py", line 230, in request
    return walk(self._in, self._session.request(name, *args, **kwargs),
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py", line 90, in request
    raise self.error_wrapper(err)
NvimError: Vim(tjump):E433: No tags file
```

**Comment by blueyed** [comment] 2015-10-19 21:44
I'd guess that https://github.com/davidhalter/jedi-vim/pull/481 fixes it.

Can you try and confirm that?
Otherwise this is likely to be merged soonish anyway.

**Comment by blueyed** [comment] 2015-10-19 21:47
#481 is merged now, please re-try.

**Comment by blueyed** [comment] 2015-10-19 21:48
If it does not work, please provide a new traceback.

Thanks!

**Comment by perks** [comment] 2015-10-19 21:51
Pulled and retried, still suffering same error:

```
Traceback (most recent call last):
  File "/home/chris/.vim/plugged/jedi-vim/jedi_vim.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/home/chris/.vim/plugged/jedi-vim/jedi_vim.py", line 264, in goto
    vim.command('tjump %s' % tagname)
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/nvim.py", line 119, in command
    return self._session.request('vim_command', string, async=async)
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/common.py", line 230, in request
    return walk(self._in, self._session.request(name, *args, **kwargs),
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py", line 90, in request
    raise self.error_wrapper(err)
NvimError: Vim(tjump):E433: No tags file
```

Any other debug info I can provide let me know

**Comment by blueyed** [comment] 2015-10-19 22:17
Thanks for your additional information!

I cannot look into this more deeply today, but I'm sure we'll get this resolved.. :)

/cc @wilywampa

**Comment by perks** [comment] 2015-10-19 22:37
No problem, best of luck!

**Comment by wilywampa** [comment] 2015-10-20 00:51
I was looking forward to another night of debugging but I can't reproduce the issue. This is my entire `.nvimrc`:

```vim
let g:jedi#use_tag_stack = 1
nnoremap <M-]> :<C-u>call jedi#goto()<CR>zv
```

and neovim `:version`:
```
NVIM 0.0.0-alpha+201510171857 (compiled Oct 18 2015 09:27:28)
Commit: e9de70e4ea53cd7ab70eba0757309004c61c3c62
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE
_CONFIG_H -I/tmp/neovim20151018-40144-bcjknq/build/config -I/tmp/neovim20151018-40144-bcjknq/src -I/tmp/neovim20151018-40144-bcjknq/deps-build/usr/include -I/tmp/neovim20151018-40144-bcjknq/deps-build/usr/include -I/tmp/neovim20151018-401
44-bcjknq/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151018-40144-bcjknq/deps-build/usr/include -I/tmp/neovim20151018-40144-bcjknq/deps-build/usr/include -I/tmp/neovim20151018-40144-bcjknq/deps-build/usr/include -I/tmp/neovim2015101
8-40144-bcjknq/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20151018-40144-bcjknq/build/src/nvim/auto -I/tmp/neovim20151018-40144-bcjknq/build/include
Compiled by jniehus@MacBook-Pro

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
```

and gratuitous video evidence:
![tagstack](https://cloud.githubusercontent.com/assets/4472522/10595180/f360651e-7689-11e5-913e-ea0dc0837715.gif)

**Comment by perks** [comment] 2015-10-20 01:09
@wilywampa @blueyed 

So doing some bisect work, I figured out the line that was causing the crash:
```
set wildignore+=*.swp,*~,._*,*/tmp/*,.DS_Store
```

Using nothing but a nvimrc of:
```
""""""""""""""""""""
" User Plugins
""""""""""""""""""""
call plug#begin('~/.vim/plugged')

Plug 'davidhalter/jedi-vim'

call plug#end()

""""""""""""""""""""""""""""""
" Keybindings
""""""""""""""""""""""""""""""
let mapleader=","
let localmapleader=","

" Disable temp and backup files
set wildignore+=*.swp,*~,._*,*/tmp/*,.DS_Store
```

Removing the offending line caused functionality to work as normal, I guess this is because of the new temporary file creation a la #481 

Must have set wildignore before to help with indexing and pass over tmp files,  doh!

Thanks everyone for the help! Feel free to mark this closed if you'd like.

**Comment by blueyed** [comment] 2015-10-20 08:29
I think we should temporarily (un)set 'wildignore' then, or find a way to make it work with it.

Does the issue exist also for Vim?

**Comment by wilywampa** [comment] 2015-10-20 14:01
I can't reproduce the problem in neovim or vim even after making that change to `wildignore`. My neovim build is only 2 days old so I wonder if it was a bug that was fixed. Can anyone else try?

**Comment by jbkopecky** [comment] 2015-10-21 10:10
My goto function in vim is also broken since last update.

I have tried to disable wildignore without success.

```
Traceback (most recent call last):
 File "C:\Users\JKY\.vim\plugged\jedi-vim\jedi_vim.py", line 118, in wrapper
    return func(*args, **kwargs)
 File "C:\Users\JKY\.vim\plugged\jedi-vim\jedi_vim.py", line 264, in goto
    vim.command('tjump %s' % tagname)
error: Vim(tjump):E433: No tags file
```

Note: I have the same issue on my Linux Config

**Comment by wilywampa** [comment] 2015-10-21 15:07
I still haven't been able to reproduce the issue but I have a good hypothesis. That traceback is exactly what I see if use a tags file with spaces in its name. Can you try replacing this line: https://github.com/davidhalter/jedi-vim/blob/master/jedi_vim.py#L263

with:
```python
vim.command('let &tags = %s' % repr(PythonToVimStr(f.name.replace(' ', r'\ '))))
```

**Comment by jbkopecky** [comment] 2015-10-21 15:14
I have tried this fix but it doesn't fix it or change the error output.

**Comment by perks** [comment] 2015-10-21 16:04
@jbkopecky does it still happen if you load a .vimrc with *just* jedi-vim loaded?

If not, you can bisect your .vimrc: (see http://albertogrespan.com/blog/debugging-your-vimrc/)

**Comment by wilywampa** [comment] 2015-10-21 16:31
I can finally reproduce using `set wildignore+=*/tmp/*,*.so,*.swp,*.zip` from @jbkopecky's vimrc so I'll figure out what's happening.

**Comment by wilywampa** [comment] 2015-10-21 16:52
It turns out the `tags` setting is not a list of files but a list of patterns and `wildignore` is used whenever file patterns are involved. That means even if a full file name is given for a file instead of a glob pattern, it still matches `wildignore` and is ignored. I agree the fix for that is to unset and then restore `wildignore` when jumping to a tag.

As for this:
>any successive jumps seemingly jump to random locations in the buffer

That's because the `new_buffer()` call [here](https://github.com/davidhalter/jedi-vim/blob/master/jedi_vim.py#L252) is always passing `using_tagstack=True` but it should really depend on the value of `g:jedi#use_tag_stack`. When that happens, it should have opened a different buffer but did not, so it tries to jump to a line/column in the wrong buffer.

I'll make those changes (unset `wildignore` and `using_tagstack=vim_eval('g:jedi#use_tag_stack') == '1'` and add tests for both tonight.

**Comment by jbkopecky** [comment] 2015-10-22 07:44
Thanks !

**Closed** 2015-10-22 22:32 UTC
Labels: bug

**Comment by jarmangani** [comment] 2015-10-30 14:57
I still have the same problem despite having plugin updated with fix 483. Every time I use goto function get the following stack trace:

Traceback (most recent call last):
 File "C:\Users\xxx\.vim\plugged\jedi-vim\jedi_vim.py", line 118, in wrapper
    return func(*args, **kwargs)
 File "C:\Users\xxx\.vim\plugged\jedi-vim\jedi_vim.py", line 269, in goto
    vim.command('tjump %s' % tagname)
error: Vim(tjump):E433: No tags file

I use Windows version of VIM 7.4. Have updated plugin yesterday and since then I experience this issue.

**Comment by jbkopecky** [comment] 2015-10-30 15:24
Hello,
I have the same issue. For now, I am using the following setting in my vimrc: 
```
let g:jedi#use_tag_stack = 0 
```
which works even with last commits.
I am not sure but I think that I have issues with my ctag files, so this settings somehow prevent any fallback on tag files usage.
This definitely does not fix the bug, but could we avoid it with a "Try tags files and ignore" if there is no file ?

**Comment by jarmangani** [comment] 2015-10-30 15:29
Thank you. This workaround seems to work for me.

**Comment by wilywampa** [comment] 2015-10-30 17:16
This is kind of a shot in the the dark but can you try this branch? https://github.com/wilywampa/jedi-vim/tree/goto_wildignore

I updated the way `'tags'` and `'wildignore'` are set so it escapes strings properly. Maybe there are backslashes in the temp file name, although that seems unlikely unless you're running on Windows.

**Comment by wilywampa** [comment] 2015-10-30 17:29
@jarmangani Wow, my reading comprehension is lacking today. You are in fact using Windows, so I think that branch has a pretty good chance of fixing the problem.

@jbkopecky Are you seeing the problem in Windows as well?

**Comment by wilywampa** [comment] 2015-10-30 18:21
That didn't fix it, but I was able to reproduce the problem and fix it for real. [Windows doesn't play well with `NamedTemporaryFile`](https://bugs.python.org/issue14243) so I wrote a simple context manager to handle the file in a way that works everywhere.

This should be fixed by PR https://github.com/davidhalter/jedi-vim/pull/489.
