### ISSUE TITLE
Conceiled callback signatures might confuse syntax highlighting

### ISSUE THREAD

**Issue by derenio** [davidhalter/jedi-vim#228] opened 2013-12-10 17:19 UTC
If you are completing function's parameters and the hint pops up on the line above it that:
    1) contains a string literal,
    2) ends with a comment that contains same string literal constructor (`'` or `"`)
the syntax highlighting will treat the code from the popup to the end of the file as a string literal.

Example:

```
from functools import partial

s = 'this must be long enough'  # this' a culprit
f = partial()
this_will_be_a_string_according_to_syntax_on_partial_prototype_completion = True
```

**Comment by blueyed** [comment] 2018-07-28 04:38
It is not clear to me what the reproduce steps here are.

Triggering the call signature on `f = partial(` seems to look fine by now.

It looks like this then:
```
from functools import partial
           (func, *args, **keywords) 
s = 'this  (args, kwargs) '  # this' a culprit
f = partial(                                                                                 
this_will_be_a_string_according_to_syntax_on_partial_prototype_completion = True
```

`this_will_be_a_string_according_to_syntax_on_partial_prototype_completion` is not highlighted as a string.

Otherwise #652 might help maybe.

**Comment by blueyed** [comment] 2018-07-28 04:39
Closing since I assume that this is fixed already, please re-open otherwise.

**Closed by blueyed** 2018-07-28 04:39 UTC
Labels: bug
