### ISSUE TITLE
jedi#rename in splitted windows spawns a new tab

### ISSUE THREAD

**Issue by mota** [davidhalter/jedi-vim#150] opened 2013-07-10 15:03 UTC
First of all, thanks for this kick-ass plugin!

When I try to rename an identifier on a splitted window, on completion (i.e: exiting the insert mode), with use_tabs_not_buffers set to 1, jedi spawns a new tab of the current buffer.

When use_tabs_not_buffers is set to 0, the following error occurs:

```
Error detected while processing function jedi#rename..jedi#new_buffer:
line    7:
E37: No write since last change (add ! to override)
Error detected while processing function jedi#rename..jedi#new_buffer:
line    7:
Traceback (most recent call last):
Error detected while processing function jedi#rename..jedi#new_buffer:
line    7:
  File "<string>", line 1, in <module>
Error detected while processing function jedi#rename..jedi#new_buffer:
line    7:
vim.error
```

When I delete the jedi#new_buffer call at the end of the jedi_vim.rename function (plugin/jedi_vim.py line 310 on commit 380ab946e5432a522307ff5bf733064979c8fa55), everything works as I expected.

I don't have a deep understanding of how the plugin works, so I assume my fix proposal is not elegant, but seems to do the job for now.

**Comment by leebrooks0** [comment] 2015-01-16 06:28
I am also running into this issue, i rename something and then a new tab opens. I then chose to use buffers not tabs and then after renaming the syntax highlighting is removed?

**Comment by davidhalter** [comment] 2015-01-16 09:19
I know the issue. I have no idea where it comes from or how we can resolve it. Probably a nasty VIM bug. VIM script just sucks.

**Comment by blueyed** [comment] 2015-06-26 15:36
Should be fixed by now, mainly via https://github.com/davidhalter/jedi-vim/pull/403.

Please re-open / report back in case it's still an issue.

**Comment by blueyed** [comment] 2015-06-26 15:38
Oh, that's with `use_tabs_not_buffers=1`, which might be something different.

The reason might be that an existing tab that should be re-used isn't found properly.

Re-opening it for now.  Please test with the latest version and provide a test case to reproduce it.

**Comment by blueyed** [comment] 2018-07-28 04:31
Closing, assuming that it was fixed.  Please re-open otherwise.

**Closed by blueyed** 2018-07-28 04:31 UTC
Labels: bug
