### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'names_dicts'

### ISSUE THREAD

**Issue by oblitum** [davidhalter/jedi-vim#485] opened 2015-10-23 15:36 UTC
I have enabled internal jedi debugging in the following output:

```
dbg: Parsed foo.py, with 8 parsers in 8 splits.
warning: No statement under the cursor.
dbg: eval_element <Name: cv2@38,16>@(38, 16)
dbg: finder.filter_name "<Name: cv2@38,16>" in (<ModuleWrapper: <fast.FastModule: bar@1-44>>): u'[<Name: cv2@4,7>]'@(38, 16)
dbg: search_module 'cv2' in 'foo.py'
Error detected while processing function jedi#completions:
line    1:
ImportError: numpy.core.multiarray failed to import
warning: Module '/usr/lib/python2.7/dist-packages/cv2.so' not importable.
dbg: after import: [None]
dbg: finder._names_to_types: [<Name: cv2@4,7>] -> [None]
dbg: possible completion scopes: [None]
Traceback (most recent call last):
  File "/home/francisco/.vim/plugged/jedi-vim/jedi_vim.py", line 182, in completions
    completions = script.completions()
  File "/home/francisco/.vim/plugged/jedi-vim/jedi/jedi/api/__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "/home/francisco/.vim/plugged/jedi-vim/jedi/jedi/api/__init__.py", line 178, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/home/francisco/.vim/plugged/jedi-vim/jedi/jedi/api/__init__.py", line 259, in _simple_complete
    for names_dict in s.names_dicts(search_global=False):
AttributeError: 'NoneType' object has no attribute 'names_dicts'
```

This AttributeError keeps popping up anytime I type `cv2.` on Ubuntu, I didn't checked it but on Arch at home I have no issues, anyways, not ranging `None` would mute it. Despite this, it would be nice to be able to complete `cv2.`.

**Comment by oblitum** [comment] 2015-10-23 16:50
I was able to solve my problem with opencv and numpy, I'm using virtualenvs through pyenv, [also in vim](https://github.com/lambdalisue/vim-pyenv).

I realized that I could only install a precompiled opencv through apt-get, which comes with python bindings as well, and they're installed to the infamous Ubuntu "dist-packages", instead of the commonly adopted "site-packages". There's no precompiled opencv python bindings to install through pip in a virtualenv, and hence to work with the system's one I've currently opted to use `.pth` files to inherent the system's packages in "dist-packages" into the virtualenv. So to get opencv bindings inside this virtualenv aswell.

Formally I had installed a recent numpy in this virtualenv, which is one of the dependecies to work with the opencv's cv2 interface, I just realized it'd be better to use the system's numpy from "dist-packages" instead of a new one, since I'm using it at the moment to work with opencv.

So I've uninstalled numpy from my virtualenv and completion is working fine both for opencv as for numpy.

Despite this, I'll let this issue open at your option to close it, since not ranging `None` may be an improvement regardless of the context. Even after fixing this locally I still got the `ImportError: numpy.core.multiarray failed to import` error, which ended up solved the way I've explained.

**Comment by davidhalter** [comment] 2015-10-23 16:51
Well, it's still a Jedi issue, no matter if you fixed it by installing something else.

**Comment by oblitum** [comment] 2015-10-23 16:54
@davidhalter ok, notice the issue happened with all stuff already installed, it was by uninstalling (numpy from local virtualenv) that it started to work, just saying for the case of reproduction of the issue.

**Comment by oblitum** [comment] 2015-10-23 17:54
Well... in the end I'm still struggling with this, now setup is ok for the editor, but try to run the given python script give `numpy.core.multiarray` errors, if I let the setup so that I can run the script, the editor doesn't work...

**Comment by oblitum** [comment] 2015-10-23 18:03
I've checked everything works, editor and running script, when using everything system, no virtualenvs... so I'm almost giving up using virtualenv in this case of `.so` dependencies, opencv, etc.

**Comment by oblitum** [comment] 2015-10-23 18:23
Victory!
Ok, I'm building reports here just in case anyone on the web get into the same rabbit hole.

I've wiped out my old virtualenv based on a given fixed python version and created another anew based on the one from the system with:

`pyenv virtualenv --python=/usr/bin/python2.7 foo`

Notice that I have to put `/usr/bin/python2.7` not `/usr/bin/python2` or `/usr/bin/python`, I've gone through previous issues doing that before.

Using a virtualenv based on system's python, I still have to use `.pth` files to inherent system's "dist-packages", because... Ubuntu.

This way, everything is working.

**Comment by ramnath-k** [comment] 2015-12-12 12:39
I got the same error when I used the vim installed by using apt-get in Ubuntu 14.04 whereas I had compiled opencv for a virtualenv version of python (numpy was also in the virtualenv).
I then proceeded to compile vim from source using the steps given at https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source
#### install vim dependencies
sudo apt-get remove vim vim-runtime gvim
sudo apt-get remove vim-tiny vim-common vim-gui-common
sudo apt-get install libncurses5-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev ruby-dev git
#### vim compile from source
export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib/
cd ~
git clone https://github.com/vim/vim.git
cd vim
./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp \
            --enable-pythoninterp \
            --with-python-config-dir=$VIRTUAL_ENV/lib/python2.7/config \
            --enable-perlinterp \
            --enable-luainterp \
            --enable-gui=gtk2 --enable-cscope --prefix=$VIRTUAL_ENV	
make VIMRUNTIMEDIR=$VIRTUAL_ENV/share/vim/vim74
make install

Now I am able to first activate the virtualenv, then launch the vim installed in it and autocomplete cv. nicely.

I thought this might help the original poster and also help debug the issue (which might be because numpy is in a virtualenv with a different python compared to the system python which is used to compile vim in ubuntu repos)

**Comment by davidhalter** [comment] 2015-12-13 00:51
@ramnath-k Doesn't change the fact that this is a bug and should be fixed within Jedi. But thanks for the comment!

**Comment by oblitum** [comment] 2015-12-13 01:38
@ramnath-k if you follow my comments you may check that I've solved my case, and it's a bit different of yours, I've left the procedure described here for just for anyone that happens to go through the same. My case was that I wished to use system installed opencv, since I didn't want to compile it, yours is the contrary, you're compiling it in a given virtual enviroment.

Anyways, thanks for the comment since it may help anyone going through the same.

**Comment by blueyed** [comment] 2016-03-18 22:33
For reference, I came up with https://github.com/davidhalter/jedi/pull/684 as a fix for Jedi when it hit me - but without much additional information / test case / reproduce steps.

In case you're seeing this issue, you could provide more information there.

**Comment by davidhalter** [comment] 2016-07-21 21:32
Closing, because it's cared for by davidhalter/jedi#684.

**Closed by davidhalter** 2016-07-21 21:32 UTC
Labels: bug, jedi-issue
