### ISSUE TITLE
Pattern not found for Pandas

### ISSUE THREAD

**Issue by robbyki** [davidhalter/jedi-vim#425] opened 2015-05-25 12:11 UTC
Is there something else I need to do in order to enable support for some libraries like Pandas?

**Comment by blueyed** [comment] 2015-05-25 12:26
Can you provide a test case / setup to reproduce your problem, please?

**Comment by robbyki** [comment] 2015-05-25 12:31
Just installed on centos65/vim74 and everything works great when editing file in vim for standard libs but for some reason when I do `import pandas as pd` I was expecting to get auto-complete after using `pd.` but nothing comes up even after trying Ctrl+Space. Let me know if other info is needed.

**Comment by blueyed** [comment] 2015-05-25 15:34
Works for me.

In a temporary Python 3.4 virtualenv, with "pip install pandas" I get the
expected completions:

    algos                   module: pandas.algos
    Appender                class: pandas.util.decorators.Appender
    bdate_range             function: pandas.tseries.index.bdate_rang
    Categorical             class: pandas.core.categorical.Categorica
    CategoricalIndex        class: pandas.core.index.CategoricalIndex
    compat                  module: compat
    computation             module: computation
    concat                  function: pandas.tools.merge.concat
    core                    module: core
    crosstab                function: pandas.tools.pivot.crosstab
    cut                     function: pandas.tools.tile.cut
    DataFrame               class: pandas.core.api.DataFrame
    date_range              function: pandas.tseries.index.date_range
    DateOffset              class: pandas.tseries.offsets.DateOffset
    datetime                class: datetime.datetime
    DatetimeIndex           class: pandas.tseries.index.DatetimeIndex

Typing the dot, which triggered the first completion attempt took a while (several seconds - and seemed to time out), but then it completed on the second try.

When restarting Vim, it took "only" 3-5 seconds then.

**Comment by robbyki** [comment] 2015-05-27 00:38
Ok thank you. Still not working for me using 3.4 with Anaconda.

**Comment by blueyed** [comment] 2015-05-27 19:32
> with Anaconda

Is there some special setup involved with this?
Does it work for you in a simple Python 3.4 virtualenv?

**Comment by davidhalter** [comment] 2015-05-28 10:58
Please post `:ver`, `:set omnifunc`, `:mes`.

**Comment by c01o** [comment] 2015-11-27 14:09
I had the same issue using python2.7 installed with anaconda2.
That was because my vim(jedi) search for plugins only in system-default python directory.
So I made my vim to search in anaconda's python, and the problem is solved. 
Try like it:

```~/.vim/ftplugin/python.vim
python << EOF
import os
import sys

home = os.path.expanduser("~")
path = home + "/anaconda2/lib/python2.7/site-packages"
if not path in sys.path:
    sys.path.insert(0, path)
EOF
```

**Comment by robbyki** [comment] 2016-02-10 12:31
Thanks. Tried adding the following but that did not work either:
```
#!/bin/bash
python3 << EOF
import os
import sys

home = os.path.expanduser("~")
path = home + "/usr/local/lib/python3.5/site-packages"
if not path in sys.path:
    sys.path.insert(0, path)
EOF
```

Here is my :version:
```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov  2 2015 16:06:52)
Included patches: 1-907
Compiled by root@ip-10-239-197-136
Huge version without GUI.  Features included (+) or not (-):
+acl             +dialog_con      +insert_expand   +mouse_sgr       -ruby            +vertsplit
+arabic          +diff            +jumplist        -mouse_sysmouse  +scrollbind      +virtualedit
+autocmd         +digraphs        +keymap          +mouse_urxvt     +signs           +visual
-balloon_eval    -dnd             +langmap         +mouse_xterm     +smartindent     +visualextra
-browse          -ebcdic          +libcall         +multi_byte      -sniff           +viminfo
++builtin_terms  +emacs_tags      +linebreak       +multi_lang      +startuptime     +vreplace
+byte_offset     +eval            +lispindent      -mzscheme        +statusline      +wildignore
+cindent         +ex_extra        +listcmds        +netbeans_intg   -sun_workshop    +wildmenu
+clientserver    +extra_search    +localmap        +path_extra      +syntax          +windows
+clipboard       +farsi           -lua             -perl            +tag_binary      +writebackup
+cmdline_compl   +file_in_path    +menu            +persistent_undo +tag_old_static  +X11
+cmdline_hist    +find_in_path    +mksession       +postscript      -tag_any_white   +xfontset
+cmdline_info    +float           +modify_fname    +printer         -tcl             -xim
+comments        +folding         +mouse           +profile         +terminfo        +xsmp_interact
+conceal         -footer          -mouseshape      -python          +termresponse    +xterm_clipboard
+cryptv          +fork()          +mouse_dec       +python3         +textobjects     -xterm_save
+cscope          +gettext         -mouse_gpm       +quickfix        +title           -xpm
+cursorbind      -hangul_input    -mouse_jsbterm   +reltime         -toolbar
+cursorshape     +iconv           +mouse_netterm   +rightleft       +user_commands
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lSM -lICE  -lm -ltinfo -lnsl  -lse
linux      -L/usr/lib64/python3.3/config-3.3m -lpython3.3m -lpthread -ldl -lutil -lm
```

**Comment by davidhalter** [comment] 2016-02-10 15:25
You're using a path from Python 3.5. It's not even supported, yet.

**Comment by robbyki** [comment] 2016-02-10 15:32
Okay. thank you.

**Comment by davidhalter** [comment] 2016-02-10 16:07
Let's wait for https://github.com/davidhalter/jedi/pull/691 to get merged.

**Comment by davidhalter** [comment] 2016-07-21 23:29
There's multiple issues in Jedi about pandas not working. Might just take some time.

**Closed by davidhalter** 2016-07-21 23:29 UTC
Labels: not-reproducible

**Comment by joelostblom** [comment] 2016-09-10 18:45
I am using python 3.5.2 with pandas installed via anaconda. Omnicompletion works for me after adding
```
export PYTHONPATH="/home/user-name/anaconda3/lib/python3.5/site-pac‌​kages":$PYTHONPATH
```
 to my `~/.zshrc` [as per this stack exchange answer](http://vi.stackexchange.com/questions/9486/how-to-change-python-interpreter-used-by-jedi-vim?newreg=54c17da945bf4482bb0c739fe2aada69)

**Comment by davidhalter** [comment] 2016-09-11 06:20
Basically the only thing you can do currently is to compile VIM with Python 3.5 support. That's probably a stupid idea, but it works.

Otherwise there will be support for cross Python versions, with https://github.com/davidhalter/jedi/issues/385.

Note that it might be possible to modify the Python PATH, but that might lead to a SEGFAULT and to other unwanted behavior, because you're basically allowing Jedi to run binary code from another Python version (Yes it actually happens).

**Comment by tmsimont** [comment] 2016-10-12 03:01
For me, pandas doesn't autocomplete in Python 2.7

However, when I type
```
import pandas.
```
I get a list of submodules. When I use a specific submodule (e.g. pandas.algos) I have no problems

The problem appears when I try to use `pandas as pd` 
```
import pandas as pd
pd.

Omni completion (^O^N^P) Pattern Not Found
```


```
:mes
Traceback (most recent call last):
  File "/home/tmsimont/.vim/bundle/jedi-vim/jedi_vim.py", line 193, in completions
    menu=PythonToVimStr(c.description),
  File "/home/tmsimont/.vim/bundle/jedi-vim/jedi/jedi/api/classes.py", line 425, in description
    t = self.type
  File "/home/tmsimont/.vim/bundle/jedi-vim/jedi/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/home/tmsimont/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/tmsimont/.vim/bundle/jedi-vim/jedi/jedi/api/classes.py", line 499, in follow_definition
    return [Definition(self._evaluator, d.name) for d in defs]
AttributeError: 'NoneType' object has no attribute 'name'
```

```
:ver
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  2 2016 05:20:25)
Included patches: 1-2143
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             +cscope          -footer          +menu            +num64           +startuptime     +virtualedit
+arabic          +cursorbind      +fork()          +mksession       +packages        +statusline      +visual
+autocmd         +cursorshape     +gettext         +modify_fname    +path_extra      -sun_workshop    +visualextra
-balloon_eval    +dialog_con      -hangul_input    +mouse           +perl/dyn        +syntax          +viminfo
-browse          +diff            +iconv           -mouseshape      +persistent_undo +tag_binary      +vreplace
++builtin_terms  +digraphs        +insert_expand   +mouse_dec       +postscript      +tag_old_static  +wildignore
+byte_offset     -dnd             +job             +mouse_gpm       +printer         -tag_any_white   +wildmenu
+channel         -ebcdic          +jumplist        -mouse_jsbterm   +profile         +tcl/dyn         +windows
+cindent         +emacs_tags      +keymap          +mouse_netterm   +python/dyn      +termguicolors   +writebackup
-clientserver    +eval            +lambda          +mouse_sgr       +python3/dyn     +terminfo        -X11
-clipboard       +ex_extra        +langmap         -mouse_sysmouse  +quickfix        +termresponse    -xfontset
+cmdline_compl   +extra_search    +libcall         +mouse_urxvt     +reltime         +textobjects     -xim
+cmdline_hist    +farsi           +linebreak       +mouse_xterm     +rightleft       +timers          -xsmp
+cmdline_info    +file_in_path    +lispindent      +multi_byte      +ruby/dyn        +title           -xterm_clipboard
+comments        +find_in_path    +listcmds        +multi_lang      +scrollbind      -toolbar         -xterm_save
+conceal         +float           +localmap        -mzscheme        +signs           +user_commands   -xpm
+cryptv          +folding         +lua/dyn         +netbeans_intg   +smartindent     +vertsplit
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-pr
otector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl
,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vi
m        -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,
--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lp
thread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm
```

```
 omnifunc=jedi#completions 
```

```
:py import sys; print sys.path 
['/home/tmsimont/.vim/bundle/jedi-vim', '/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/site-p
ackages', '/usr/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg', '/usr/lib/python2.7/site-packages/scip
y-0.18.0-py2.7-linux-x86_64.egg', '/usr/lib/python2.7/site-packages/gtk-2.0', '_vim_path_']
```

From Pyhon REPL:

```
Python 2.7.12 (default, Jun 28 2016, 08:31:05) 
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.__file__
'/usr/lib/python2.7/site-packages/pandas/__init__.pyc'

```

**Comment by blueyed** [comment] 2016-10-12 09:52
IIRC Pandas is not easy to support, and there are issues: please refer to the Jedi repo: https://github.com/davidhalter/jedi.
