### ISSUE TITLE
Omni Completion problem

### ISSUE THREAD

**Issue by sudarshansudarshan** [davidhalter/jedi-vim#897] opened 2018-12-29 20:13 UTC
I get this error Omni completion (^O^N^P) Pattern not found when I execute the following code:

import numpy
numpy.

At this stage the error appears and doesn't show any autocompletion.

My :version output is here

[version.txt](https://github.com/davidhalter/jedi-vim/files/2716688/version.txt)

My :JediDebugInfo output is here

[jedidebuginfo.txt](https://github.com/davidhalter/jedi-vim/files/2716689/jedidebuginfo.txt)

**Comment by LiSongcheng** [comment] 2019-01-01 16:48
Same problem, and it happens with both built-in python modules and numpy. 

This is my **:message**:

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 253, in completions
    completions = script.completions()
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 176, in completions
    self._evaluator, self._get_module(), self._code_lines,
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 148, in _get_module
    import_names = dotted_path_in_sys_path(self._evaluator.get_sys_path(), self.path)
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/evaluate/__init__.py", line 126, in get_sys_path
    return self.project._get_sys_path(self, environment=self.environment)
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/project.py", line 104, in _get_sys_path
    sys_path = list(self._get_base_sys_path(environment))
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/project.py", line 88, in _get_base_sys_path
    sys_path = list(environment.get_sys_path())
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 128, in get_sys_path
    return self._get_subprocess().get_sys_path()
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 20
2, in get_sys_path
    return self._send(None, functions.get_sys_path, (), {})
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 24
2, in _send
    is_exception, traceback, result = pickle_load(self._process.stdout)
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/_compatibility.py", line 464, in pickle_load
    return pickle.load(file, encoding='bytes')
_pickle.UnpicklingError: invalid load key, '\x1b'.
Traceback (most recent call last):
  File "/Users/kenichian/.vim/bundle/jedi-vim/pythonx/jedi/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())
```

In addition, my vim is compiled with python3 only, and I'm not using any pyenv stuff.

**Comment by blueyed** [comment] 2019-01-02 04:37
Duplicate of #870.

**Closed by blueyed** 2019-01-02 04:37 UTC

**Comment by Millani** [comment] 2019-01-22 02:42
@blueyed I am having the same problem as described here by the OP. You closed this saying it's a duplicate of #870, but I don't see anywhere in the long discussion there any mention to the specific problem described here - i.e. the "Omni completion (^O^N^P) Pattern not found" error without any window popping up. Would you mind giving us a bit of context on why are those issues related?

**Comment by sudarshansudarshan** [comment] 2019-01-22 02:46
I second Millani. Even I couldn’t figure out from #870

**Comment by blueyed** [comment] 2019-01-22 10:54
I commented on the previous comment:

> _pickle.UnpicklingError: invalid load key, '\x1b'.

The OP's traceback also has:

> ERROR: failed to get sys path from environment: jedi.api.environment.InvalidPythonEnvironment: Could not get version information for '/usr/local/bin/vim': UnpicklingError("invalid load key, '\\x1b'.")

**Comment by AndresCasado** [comment] 2019-01-24 15:10
I get `Omni completion (^O^N^P) Pattern not found` too and I can't find how to solve it in issue #870, which seems something Windows-related, and I'm on Ubuntu 16.04.

To trigger it I just write:
```
import numpy
a = numpy.array([1,2])
a.
```

This is my `:version`:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Parches incluidos: 1-1689
Parches adicionales: 8.0.0056
Modificado por pkg-vim-maintainers@lists.alioth.debian.org
Compilado por pkg-vim-maintainers@lists.alioth.debian.org
Versión "enorme" sin interfaz gráfica (GUI).  Aspectos incluidos (+) o no (-):
+acl             +dialog_con      +job             -mouse_sysmouse  +scrollbind      +visual
+arabic          +diff            +jumplist        +mouse_urxvt     +signs           +visualextra
+autocmd         +digraphs        +keymap          +mouse_xterm     +smartindent     +viminfo
-balloon_eval    -dnd             +langmap         +multi_byte      +startuptime     +vreplace
-browse          -ebcdic          +libcall         +multi_lang      +statusline      +wildignore
++builtin_terms  +emacs_tags      +linebreak       -mzscheme        -sun_workshop    +wildmenu
+byte_offset     +eval            +lispindent      +netbeans_intg   +syntax          +windows
+channel         +ex_extra        +listcmds        +packages        +tag_binary      +writebackup
+cindent         +extra_search    +localmap        +path_extra      +tag_old_static  -X11
-clientserver    +farsi           +lua             +perl            -tag_any_white   -xfontset
-clipboard       +file_in_path    +menu            +persistent_undo +tcl             -xim
+cmdline_compl   +find_in_path    +mksession       +postscript      +terminfo        -xsmp
+cmdline_hist    +float           +modify_fname    +printer         +termresponse    -xterm_clipboard
+cmdline_info    +folding         +mouse           +profile         +textobjects     -xterm_save
+comments        -footer          -mouseshape      -python          +timers          -xpm
+conceal         +fork()          +mouse_dec       +python3         +title
+cryptv          +gettext         +mouse_gpm       +quickfix        -toolbar
+cscope          -hangul_input    -mouse_jsbterm   +reltime         +user_commands
+cursorbind      +iconv           +mouse_netterm   +rightleft       +vertsplit
+cursorshape     +insert_expand   +mouse_sgr       +ruby            +virtualedit
     archivo "vimrc" del sistema: "$VIM/vimrc"
     archivo "vimrc" del usuario: "$HOME/.vimrc"
  2º archivo "vimrc" del usuario: "~/.vim/vimrc"
      archivo "exrc" del usuario: "$HOME/.exrc"
            predefinido para $VIM: "/usr/share/vim"
Compilación: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werr
or=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Enlazado: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -
Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselin
ux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_
64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -l
python3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3
-lpthread -lgmp -ldl -lcrypt -lm
```

This is my `:JediDebugInfo`:
#### Jedi-vim debug information

##### jedi-vim version

 - jedi-vim git version: 0.9.0-62-g7f4f2db
 - jedi git submodule status:  bd1010bbd2693f189ff780eb21fc4294071cb280 pythonx/jedi (v0.13.1)
 - parso git submodule status:  930ec08ab0cd77aae07e24aa78f9c5119be216bb pythonx/parso (v0.3.1-7-g930ec08)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.5.2 (default, Nov 12 2018, 13:43:14), [GCC 5.4.0 20160609]`
 - global site module: `/usr/lib/python3.5/site.py`

##### Jedi

 - path: `/home/andrescasado/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.13.1

##### Jedi environment: <SameEnvironment: 3.5.2 in /usr>

 - executable: /usr/bin/python3
 - sys_path:
    - `/usr/lib/python35.zip`
    - `/usr/lib/python3.5`
    - `/usr/lib/python3.5/plat-x86_64-linux-gnu`
    - `/usr/lib/python3.5/lib-dynload`
    - `/usr/local/lib/python3.5/dist-packages`
    - `/usr/local/lib/python3.5/dist-packages/setuptools-39.1.0-py3.5.egg`
    - `/usr/lib/python3/dist-packages`

##### Known environments

 - <Environment: 3.7.1 in /usr/local> (/usr/local/bin/python3.7)
 - <Environment: 3.5.2 in /usr> (/usr/bin/python3.5)
 - <Environment: 2.7.12 in /usr> (/usr/bin/python2.7)

##### Settings

```
  omnifunc=jedi#completions
        Se definió por última vez en ~/.vim/bundle/jedi-vim/autoload/jedi.vim
  completeopt=menuone,longest,preview
        Se definió por última vez en ~/.vim/bundle/jedi-vim/plugin/jedi.vim
```

**Comment by blueyed** [comment] 2019-01-24 16:04
@AndresCasado 
Yes, no reason to hijack another issue (with a bad title).
Make sure that `numpy` is available with your Vim / virtualenv etc, and consider filing a new issue instead.
