### ISSUE TITLE
Terminal (iTerm2) not restored properly with redir-completeopt check

### ISSUE THREAD

**Issue by meren** [davidhalter/jedi-vim#721] opened 2017-06-27 23:27 UTC
I'm using vim 8.0 with latest iTerm2 stable release on an up-to-date Sierra Mac OSX.

AFAICS, this issue is related to commit 6411de0cd1d2a2959f5a0bf977b3f8ecea2209d0.

When I clear my terminal (CTRL+L), open a long file with vim and quit, my cursor is at the very end of the window and the rest of the terminal is filled with blank lines. When I go one commit back in the jedi-vim repo,

```
cd ~/.vim/bundle/jedi-vim
git checkout e2d79c6434f940a21c75bb86d84b9a4d88f86209
```

the behavior is not there anymore and all is golden.

Thank you very much for the awesome software, and I apologize for the shitty bug report.

```
vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 23 2017 15:23:28)
MacOS X (unix) version
Included patches: 1-663
Compiled by meren@As-MacBook-Pro.local
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
-cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa     -L/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation
```

**Comment by blueyed** [comment] 2017-06-27 23:33
Please try if using a bang with the `silent` fixes it:
`silent! verb set completeopt?`

**Comment by meren** [comment] 2017-06-28 15:37
This change unfortunately did not fix it:

``` diff
diff --git a/plugin/jedi.vim b/plugin/jedi.vim
index 6fe1bcc..9bafa5b 100644
--- a/plugin/jedi.vim
+++ b/plugin/jedi.vim
@@ -17,7 +17,7 @@ if get(g:, 'jedi#auto_vim_configuration', 1)

     " Change completeopt, but only if it was not set already.
     redir => completeopt
-        silent verb set completeopt?
+        silent! verb set completeopt?
     redir END
     if len(split(completeopt, '\n')) == 1
         set completeopt=menuone,longest,preview
```

**Comment by blueyed** [comment] 2017-06-28 15:50
But commenting the "redir" block / replacing it by `let completeopt = ''` fixes it?

**Comment by meren** [comment] 2017-06-28 16:02
Yes, this fixes it:

``` diff
diff --git a/plugin/jedi.vim b/plugin/jedi.vim
index 6fe1bcc..eb71e78 100644
--- a/plugin/jedi.vim
+++ b/plugin/jedi.vim
@@ -16,9 +16,7 @@ if get(g:, 'jedi#auto_vim_configuration', 1)
     filetype plugin on

     " Change completeopt, but only if it was not set already.
-    redir => completeopt
-        silent verb set completeopt?
-    redir END
+    let completeopt = ''
     if len(split(completeopt, '\n')) == 1
         set completeopt=menuone,longest,preview
     endif
```

If it is any relevant, when I check the content of my `completeopt` from pristine master via `echo(expand(completeopt))` it returns `completeopt=menu,preview`. When I replace completeopt with `"menu,preview"` in the silent line, it fixes it, too.

**Comment by blueyed** [comment] 2017-06-28 20:58
Thanks for the extra info.

So the problem itself is that the screen is not restored properly when quitting Vim again, right?
Does it really depend on the length of the file, or does it also happen after `vim t.py`, where `t.py` does not exist?

**Comment by meren** [comment] 2017-06-28 22:53
> So the problem itself is that the screen is not restored properly when quitting Vim again, right? 

Yes.

> Does it really depend on the length of the file

No :/ It does happen regardless of the file size (i.e., you start vim with or without a filename parameter, quit, and your cursor is at the very end of the screen).

Thanks,

**Comment by blueyed** [comment] 2017-06-28 23:55
Unfortunately I cannot reproduce it.. :/

I've tried both 8.0.628 and 8.0.663 (current master).

I am using rxvt-unicode as terminal emulator.
Can you try another one yourself?

**Comment by blueyed** [comment] 2017-06-29 00:01
How do you load the plugin?

Does it happen with a minimal vimrc, based on this?
```vim
set nocompatible

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

syntax on
filetype plugin indent on
```

(save it as `minimal.vimrc` and then use it with `vim -Nu minimal.vimrc`.

**Comment by meren** [comment] 2017-06-29 00:51
With `minimal.vimrc` the terminal is restored beautifully.

I use pathogen if it is any relevant. But the fact that changing one line from the last commit fixes this behavior makes me feel like it is not about something outside of jedi. I am sorry this turns out to be a crappy bug to deal with. If you can't reproduce, I will assume it is about my system and continue using e2d79c6434f940a21c75bb86d84b9a4d88f86209 :)

Best,

**Comment by blueyed** [comment] 2017-06-29 08:06
Something in your setup is causing it, e.g. another plugin.
I am interested in the reaso.
I suggest bisecting your config, i.e. try to find the setting or other plugin trigerring it.

**Comment by meren** [comment] 2017-06-29 14:19
I took every plugin out one by one from the directory except jedi-vim. The problem persisted. Then, starting with an empty plugin folder, this time I put every plugin one by one into it, and the behavior was not there until jedi-vim was in. Finally, after confirming everything works as expectedly with an empty plugin folder, I only put jedi-vim, in, and the problem appeared again. Then I started going back in jedi-vim revisions using `git checkout` in the master repo, and linked the problem to the last commit, and finally particularly to line that starts with `silent`.

I scienced the crap out of this with controlled experiments, including playing with the config file, because I like procrastination and these issues fascinate me, and everything boiled down to that one line in the latest commit. Probably I could have done a much better job if I was familiar with the vim codebase or had an extensive understanding of jedi-vim, but unfortunately I don't :(

I am satisfied that this is not a general issue with jedi-vim, and instead due to my system, so there is no big concern. My purpose was to report something that might help fixing a general issue for altruistic reasons. Since it is not a critical issue, and we don't have infinite time, I will close this issue with your permission.

Thank you very much for your time and attention.


Best,

**Comment by blueyed** [comment] 2017-06-29 14:23
@meren 
You havent' started / gone back from/to your other config settings?!
There is likely some Vim setting you are using that causes this.

> My purpose was to report something that might help fixing a general issue for altruistic reasons.

Very much appreciated and understood.

And I would still like to figure out what happens/causes this, if you would like to procastinate more on that.. ;)

**Comment by meren** [comment] 2017-06-29 14:27
I will continue playing, and will let you know if I ever understand what it is interfering or find a reasonable way for you to reproduce :) Thanks again.

**Comment by davidhalter** [comment] 2017-06-29 18:40
@meren Thanks for trying!! Really appreciated.

**Comment by Zaharid** [comment] 2017-08-01 07:47
I have the same issue with the terminal app on Linux Mint. I load the plugin via Vundle. Making jedi-vim the only plugin doesn't fix the issue for me either. The same happens if I use the bash or the fish shell. I didn't find an option that restores the behaviour apart from disabling the plugin. The problem happens every time I run vim, regardless of what the file is.

**Comment by blueyed** [comment] 2017-08-01 09:43
@Zaharid 
Have you tried the minimal vimrc from above?

**Comment by Zaharid** [comment] 2017-08-01 13:09
Just did and the problem persists.

**Comment by blueyed** [comment] 2017-08-01 14:42
@Zaharid 
What is your Vim version?

I can unfortunately not reproduce it, and previously it did not happen when using the minimal vimrc.

**Comment by blueyed** [comment] 2017-08-01 14:43
> terminal app on Linux Mint

What terminal is that?
Is it available on Arch Linux?
Have you tried another terminal, e.g. xterm, urxvt, gnome-terminal?

**Comment by Zaharid** [comment] 2017-08-02 09:22
The linux mint terminal is gnome-terminal. I see the same thing happening on xterm. My vim version is:

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm   
```

**Comment by blueyed** [comment] 2017-08-07 18:36
Could reproduce it now finally.
It only affects Vim (not Neovim) and should be fixed now.

**Closed** 2017-08-07 18:36 UTC
Labels: bug, need-information
