### ISSUE TITLE
lots of lambda definitions slow things to a crawl

### ISSUE THREAD

**Issue by gfixler** [davidhalter/jedi-vim#330] opened 2014-11-27 22:58 UTC
I've been writing a lot of lambda one-liners, many of which return lambda one-liners, like this:

times = lambda x: lambda y: x \* y

I'm playing with function composition, and make-believe currying. I can do `times(5)(7)` to multiply two numbers, or I can do `times3 = times(3)` to partially apply times, resulting in a new function that already has an argument filled in (i.e. currying).

I have a few pages of such things in a file, and a mix of regular `def foo ():'-style functions here and there. I noticed yesterday, adding some new definitions that when I opened a new line and typed`(`, everything hung. I had to open a new shell and`killall -9 vim`to get out of it, then`$ reset` to clean up the mess in the original shell. I tried everything to find the problem - rolling code back to earlier, rolling vim plugins back, launching Vim without plugins and without .vimrc, independently and together. The problem was plugins, and I narrowed it down to jedi-vim. When I remove that, and I've had to for now, the problem goes away.

I was also able to make it go away by commenting out a few chunks of lambda definition lines. I could leave the regular functions. Something about lambdas really seems to slow it down. I tried uncommenting a lambda, typing `(` on a new line, undoing, uncommenting another, typing `(` on a new line - things started to slow down quickly. I'd get more and more of a lag per test, until suddenly it was taking 10 seconds. Another uncommenting and it took too long for me to bother waiting for it. It's slowing down exponentially.

Any idea what this could be? Any chance of a fix?

**Comment by mbkupfer** [comment] 2019-10-23 23:23
Looks like this conversation went a bit off topic, not to mention almost 6 years old, but I wanted to tag in as I see this is still open and it is the closest thing to what I'm experiencing with my jedi-vim slow downs.

In my situation, I also use lambdas a lot, but I use them because they are my preferred way to index pandas dataframes. For example:

```python
dff = df.loc[lambda df: (df.A > 100) & (df.B.str.contains(r'foo')]
```
Here is an exact snippet where I keep getting a long hang time when I open the last `(`

```python
 DF_AREAS = DF.loc[
    lambda df: pd.notna(df.AREA_NAME)
    ].drop_duplicates(...# editor hangs here for a ~5 seconds
```

**Comment by davidhalter** [comment] 2019-10-25 10:07
@mbkupfer Your issue probably isn't the lambdas, but the fact that pandas completions are slow. There's a couple (or at least one) issues open in the Jedi tracker about that. The best change you have is probably the issue about creating a database index.

**Comment by davidhalter** [comment] 2019-10-25 19:30
Using this issue a bit more to nerd about programming languages :)

@gfixler I know it's years later. But: I have finally read your post. I always knew I wanted to and interestingly it came after working a bit with Haskell and Rust. IMO Haskell was a bit too mathematical in a way. I watched Dave Beazley's lambda tutorial "Lambda Calculus From the Ground Up", which was a big help to understand lambda calculus (which also helped me to understand Haskell better.

I'm planning to rewrite Jedi and Parso in Rust now. It's a very elegant and powerful language. Rust is overall just a better fit. It has no garbage collection and a very new vibrant community. I have also learned a ton about parsers/type inference/software architecture while working with Jedi, so now I can finally use Jedi as a prototype and implement it in a fast language :). Let's see if ever finish this, haha. :)

**Comment by mbkupfer** [comment] 2019-10-25 20:09
@davidhalter thanks for the quick reply on this older than old issue 😆

Any chance you could link that issue. It's a bit tricky to navigate the Jedi issue tracker.

Also, excited to see a potential rewrite of jedi in rust. You've also piqued my interest into picking up rust.

**Comment by davidhalter** [comment] 2019-10-25 21:14
https://github.com/davidhalter/jedi/issues/1059 is the issue.

About Rust: You can also stick with Python if you don't do CPU-bound stuff. But if you do CPU-bound stuff Python is very slow, so you need a fast language. C/C++ sucks, Go has no features, I don't like C#/Java too much, so Rust is pretty much what I've always wanted: A modern language without GC and some very powerful features. Have fun with it :) I still love Python though. Especially for smaller projects.

**Comment by mbkupfer** [comment] 2019-10-30 18:21
>The best change you have is probably the issue about creating a database index.

@davidhalter, it looks like the issue is still open though so I'm not sure what change you are referring to.

>Your issue probably isn't the lambdas, but the fact that pandas completions are slow.

Is it possible to ignore completions by module, or say and regex pattern?

**Comment by davidhalter** [comment] 2019-11-08 10:43
@mbkupfer I wasn't clear enough: There is no fix as of now. This is just an issue that - once fixed - will improve performance for big modules.

> Is it possible to ignore completions by module, or say and regex pattern?

No. The only thing you could theoretically do is add `pandas` to `jedi.settings.auto_import_modules`. That will probably make it fast, because it will be imported instead of statically analyzed.

**Comment by davidhalter** [comment] 2019-11-08 10:46
Also I'm closing this, the original issue was that a lot of lambdas make Jedi slow. The reason for this is probably mostly that in certain scenarios open brackets are really hard to deal with in case of error recovery. If there are a few defs/classes in between, error recovery gets a lot easier. So please just write plain old functions and you'll be fine. Also as I mentioned, for big modules, I hope to eventually implement davidhalter/jedi#1059. However this might take a long time.

Feel free to continue the discussion.

**Closed by davidhalter** 2019-11-08 10:46 UTC
Labels: discussion
