### ISSUE TITLE
Error: jedi-vim failed to initialize Python

### ISSUE THREAD

**Issue by MagicYoung** [davidhalter/jedi-vim#509] opened 2015-12-15 03:14 UTC
when I am trying to edit .py file using vim, there is always such error prompts `Error: jedi-vim failed to initialize Python: jedi#setup_py_version: Vim(pyfile):Traceback (most recent call last): (in function jedi#init_python..<SNR>28_init_python..jedi#setup_py_version, line 18)`.

for your information:
`:ver
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +dialog_con      +insert_expand   +mouse_sgr       -ruby            +vertsplit
+arabic          +diff            +jumplist        -mouse_sysmouse  +scrollbind      +virtualedit
+autocmd         +digraphs        +keymap          +mouse_urxvt     +signs           +visual
-balloon_eval    -dnd             +langmap         +mouse_xterm     +smartindent     +visualextra
-browse          -ebcdic          +libcall         +multi_byte      -sniff           +viminfo
++builtin_terms  +emacs_tags      +linebreak       +multi_lang      +startuptime     +vreplace
+byte_offset     +eval            +lispindent      -mzscheme        +statusline      +wildignore
+cindent         +ex_extra        +listcmds        +netbeans_intg   -sun_workshop    +wildmenu
-clientserver    +extra_search    +localmap        +path_extra      +syntax          +windows
-clipboard       +farsi           -lua             -perl            +tag_binary      +writebackup
+cmdline_compl   +file_in_path    +menu            +persistent_undo +tag_old_static  -X11
+cmdline_hist    +find_in_path    +mksession       +postscript      -tag_any_white   -xfontset
+cmdline_info    +float           +modify_fname    +printer         -tcl             -xim
+comments        +folding         +mouse           +profile         +terminfo        -xsmp
+conceal         -footer          -mouseshape      +python          +termresponse    -xterm_clipboard
+cryptv          +fork()          +mouse_dec       -python3         +textobjects     -xterm_save
+cscope          +gettext         +mouse_gpm       +quickfix        +title           -xpm
+cursorbind      -hangul_input    -mouse_jsbterm   +reltime         -toolbar
+cursorshape     +iconv           +mouse_netterm   +rightleft       +user_commands
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werr
or=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lac
l -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -e
xport-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
`

`[':py import sys; print sys.path
/home/xyang45/.vim/bundle/jedi-vim', '/home/xyang45/.vim/bundle/jedi-vim/jedi', '/home/xyang45/miniconda2/lib/pytho
n2.7', '/home/xyang45', '/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/py
thon2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '_vim_path_']`

I wonder if there is some conflicts with vim config?

**Comment by kiminoa** [comment] 2016-01-20 19:46
Same issue. @MagicYoung Are you on MacOS and did you recently update to el Capitan?

**Comment by blueyed** [comment] 2016-01-20 21:12
Closing as duplicate of #526.

**Closed by blueyed** 2016-01-20 21:12 UTC
