### ISSUE TITLE
g:jedi#smart_auto_mappings undefined

### ISSUE THREAD

**Issue by hexum** [davidhalter/jedi-vim#468] opened 2015-10-03 11:52 UTC
When I start vim I get this error

    Error detected while processing /home/yarkov/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim:
    line   40:
    E121: Undefined variable: g:jedi#smart_auto_mappings
    E15: Invalid expression: g:jedi#smart_auto_mappings == 1

If I set variable manually in config

    let g:jedi#smart_auto_mappings = 1

And after I got message that it should be a function.

    E117: Unknown function: jedi#smart_auto_mappings
    E15: Invalid expression: jedi#smart_auto_mappings()

Why does variable g:jedi#smart_auto_mappings compared with 1?
Where should it be declared and which type must it be?

**Comment by hexum** [comment] 2015-10-03 11:54
latest commit in version I'm using

    commit 525524b5cfd6caf01fb77a108c5c2dcfade5edc4
    Merge: bcf2452 267f667
    Author: Dave Halter <davidhalter88@gmail.com>
    Date:   Mon Sep 28 00:49:33 2015 +0200

    Merge pull request #464 from itchyny/fix-global-env-pollution
    
    make `key` and `val` script local

**Comment by blueyed** [comment] 2015-10-03 13:48
It should be set here https://github.com/davidhalter/jedi-vim/blob/master/autoload/jedi.vim#L46-L50 (which was changed to use local variables in the last merged PR).

Which Vim version are you using? (`:ver`)
Does the previous commit (bcf24529faa5979e0d67b62673429f9978c2357b) work?

**Comment by hexum** [comment] 2015-10-03 14:49
```bash
LC_ALL=C vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 17 2015 03:37:58)
Included patches: 1-826
```

    HEAD detached at bcf2452

The error is exactly the same.

**Comment by blueyed** [comment] 2015-10-03 14:55
Strange.  I cannot reproduce it.
Please check if the code from `autoload` is run, and try to add some `echom` statements to see what's going on.

**Comment by hexum** [comment] 2015-10-03 15:00
OK. I'll do it tomorrow.

**Comment by davidhalter** [comment] 2016-07-21 23:46
No reaction.

**Closed by davidhalter** 2016-07-21 23:46 UTC
Labels: need-information, not-reproducible
