### ISSUE TITLE
broken display of show_call_signatures

### ISSUE THREAD

**Issue by escher9** [davidhalter/jedi-vim#302] opened 2014-08-25 03:42 UTC
hi, I saw similar issue opened few days ago, but can't find exact one again, sorry if opening duplicate one

![screenshot_function](https://cloud.githubusercontent.com/assets/5399495/4025896/3ee978c8-2c07-11e4-9702-436fd9310163.png)
expect my vim to be above screenshot.. but 

as following
![fail](https://cloud.githubusercontent.com/assets/5399495/4025884/05a014c8-2c07-11e4-92ab-c6c920920b7e.png)

seems very near to the ideal but still trailing with ' ' (small quotes) and also flickering
![notyet](https://cloud.githubusercontent.com/assets/5399495/4025888/0ffc0d14-2c07-11e4-8296-ba822f26bb1d.png)

while typing arguments, sometimes display is flickering(on off on off...)
![ani](https://cloud.githubusercontent.com/assets/5399495/4025889/1694740e-2c07-11e4-99cc-3161b4075155.gif)
It seems that if above line is filled with some code, then flickering.

I'm sure that update to latest jedi (0.8.1_final0) and jedi-vim both.

my :ver is

![ver](https://cloud.githubusercontent.com/assets/5399495/4025965/c36298bc-2c09-11e4-81ab-fe446ffd2ada.png)

**Comment by davidhalter** [comment] 2015-03-25 14:11
Did you try? 

Also I just updated jedi-vim's split character up there (the 0 that you see are actually complicated unicode characters.

**Comment by blueyed** [comment] 2015-05-02 21:16
@davidhalter 
> It doesn't work with colorschemes.

Really? Works for me.

@escher9 
There have been fixes to this feature a few weeks ago.
Can you retry it, please?

Apart from that I've just thought that maybe a setting like `magic` or `verymagic` etc might have an influence, because patterns would be treated differently.

**Comment by davidhalter** [comment] 2015-05-03 01:33
> > It doesn't work with colorschemes.

> Really? Works for me.

Yeah, I'm probably just saying that, because it didn't work a while ago. But since you improved to the syntax file, it could work better?!

**Comment by blueyed** [comment] 2015-05-03 13:37
@davidhalter 
Ah, that makes sense then.

**Comment by SamiAhola** [comment] 2015-06-10 17:28
I could reproduce the on-off flickering effect with minimal configuration with latest Jedi and Jedi-Vim.

It seems that the code line that is masked by the signature is not analyzed anymore. For example:

      import logging
      logging.basicConfig(

here the signature of basicConfig masks the import statement causing the signature disappear when key is pressed. Now the import is no longer masked and the signature is shown again when a key is pressed. This causes the on-off effect. The problem can be fixed by introducing any line in between so that the import statement is not masked. 

The effect is not limited to import statements, but any statement that affects the signature of the edited method. This can be seen in the example presented by escher9.

**Comment by blueyed** [comment] 2015-06-10 18:27
@SamiAhola 
Thanks for analysing.
I could imagine that temporarily disabling / ignoring the concealing would be required here.  Although that might cause also some flickering then (always).  But maybe it could be wrapped / get handled in a handler where Vim would not redraw anything.

**Comment by davidhalter** [comment] 2016-07-21 23:18
@blueyed Since you've labeled it as a bug, what's the exact issue here?

**Comment by oblitum** [comment] 2016-07-22 01:50
just to let the dots connected, cc https://github.com/davidhalter/jedi-vim/pull/412

**Comment by blueyed** [comment] 2017-01-08 00:06
Please try/test #652 and provide feedback there.
See https://help.github.com/articles/checking-out-pull-requests-locally/ for help on checking it out locally.

**Comment by blueyed** [comment] 2018-07-28 04:08
JFI: #652 is still alive.

**Closed** 2018-07-28 04:08 UTC
Labels: bug
