### ISSUE TITLE
GVim instance with jedi related files opens during completions, hangs original GVim

### ISSUE THREAD

**Issue by tngreene** [davidhalter/jedi-vim#884] opened 2018-10-24 19:05 UTC
### Issue
When using Jedi's completion function, it seems that, instead of calling the jedi python library it opens the library's source instead!

### Steps to reproduce
For instance, I type some python, it starts completing, then the original gVim hangs. I switch windows enough until I find GVIM2 which has 3 buffers open.

1. `.vim\bundle\jedi-vim\pythonx\jedi\jedi\evaluate\compiled\subprocess\__main__.py`
2. `.vim\bundle\jedi-vim\pythonx\parso\"
3.  `3.6.6`

Attempting to switch to buffer 2 says its an illegal file name, closes it, and I see a NERDTree view of it.

At this point the original instance is frozen. Then, closing GVIM2, GVIM is usable again but no completion was done.

#### Minimal RC used

```
set nocompatible

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

let g:jedi#completions_enabled = 1

let g:jedi#popup_on_dot = 1
let g:jedi#popup_select_first = 0
let g:jedi#use_tabs_not_buffers = 0

let g:jedi#auto_vim_configuration = 0
let g:jedi#auto_initialization = 1

"Jedi Commands
let g:jedi#completions_command = "<C-n>"
let g:jedi#goto_command = "gd"
let g:jedi#documentation_command = "K"
let g:jedi#rename_command = "<leader>rn"
let g:jedi#usages_command = "<C-G>"

let g:jedi#show_call_signatures = "0"
let g:jedi#show_call_signatures_delay = 0
call jedi#configure_call_signatures()

syntax on
filetype plugin indent on
```

### Output of “:verbose JediDebugInfo”

```

You should run this in a buffer with filetype "python".
#### Jedi-vim debug information


##### jedi-vim version


 - jedi-vim git version: b6dfc5f
 - jedi git submodule status:  bd1010bbd2693f189ff780eb21fc4294071cb280 pythonx/jedi (v0.13.1)
 - parso git submodule status:  930ec08ab0cd77aae07e24aa78f9c5119be216bb pythonx/parso (v0.3.1-7-g930ec08)


##### Global Python


Using Python version 3 to access Jedi.
 - global sys.version: `3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]`
 - global site module: `C:\Users\Ted\Miniconda3\Lib\site.py`

##### Jedi

 - path: `C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\__init__.py`
 - version: 0.13.1

##### Jedi environment: <SameEnvironment: 3.6.6 in C:\Users\Ted\Miniconda3>


 - executable: C:\Vim\gvim.exe
ERROR: failed to get sys path from environment: jedi.api.environment.InvalidPythonEnvironment: Could not get version information for 'C:\\Vim\\gvim.exe': UnpicklingError("invalid load key, '3'.",)
  Traceback (most recent call last):
    File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi_vim_debug.py", line 71, in display_debug_info
      sys_path = environment.get_sys_path()
    File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\cache.py", line 143, in wrapper
      result = method(self, *args, **kwargs)
    File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\api\environment.py", line 128, in get_sys_path
      return self._get_subprocess().get_sys_path()
    File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\api\environment.py", line 79, in _get_subprocess
      exc))


##### Settings


```
g:jedi#popup_select_first = 0 (default: 1)
g:jedi#show_call_signatures_delay = 0 (default: 500)
g:jedi#completions_command = '<C-n>' (default: '<C-Space>')
g:jedi#rename_command = '<leader>rn' (default: '<leader>r')
g:jedi#auto_vim_configuration = 0 (default: 1)
g:jedi#usages_command = '<C-G>' (default: '<leader>n')
g:jedi#goto_command = 'gd' (default: '<leader>d')
g:jedi#show_call_signatures = '0' (default: 1)

  omnifunc=
  completeopt=menu,preview,menuone,noinsert
	Last set from ~\.vim\.vimrc
```


#### :version
```

VIM - Vi IMproved 8.1 (2018 May 17, compiled May 20 2018 15:37:12)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-9
Compiled by hp@HP-PC
Huge version with GUI.  Features included (+) or not (-):
+acl                +clientserver       +dialog_con_gui     +file_in_path       +keymap             +modify_fname       +perl/dyn           +scrollbind         -termguicolors      +visual             +xpm_w32
+arabic             +clipboard          +diff               +find_in_path       +lambda             +mouse              +persistent_undo    +signs              +terminal           +visualextra        -xterm_save
+autocmd            +cmdline_compl      +digraphs           +float              +langmap            +mouseshape         -postscript         +smartindent        -tgetent            +viminfo            
+autoservername     +cmdline_hist       +directx            +folding            +libcall            +multi_byte_ime/dyn +printer            +startuptime        -termresponse       +vreplace           
+balloon_eval       +cmdline_info       -dnd                -footer             +linebreak          +multi_lang         +profile            +statusline         +textobjects        -vtp                
-balloon_eval_term  +comments           -ebcdic             +gettext/dyn        +lispindent         +mzscheme/dyn       +python/dyn         -sun_workshop       +timers             +wildignore         
+browse             +conceal            +emacs_tags         -hangul_input       +listcmds           +netbeans_intg      +python3/dyn        +syntax             +title              +wildmenu           
++builtin_terms     +cryptv             +eval               +iconv/dyn          +localmap           +num64              +quickfix           +tag_binary         +toolbar            +windows            
+byte_offset        +cscope             +ex_extra           +insert_expand      +lua/dyn            +ole                +reltime            +tag_old_static     +user_commands      +writebackup        
+channel            +cursorbind         +extra_search       +job                +menu               +packages           +rightleft          -tag_any_white      +vertsplit          -xfontset           
+cindent            +cursorshape        +farsi              +jumplist           +mksession          +path_extra         +ruby/dyn           +tcl/dyn            +virtualedit        -xim                
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /MD -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DGLOBAL_IME -DFEAT_MBYTE -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python36.dll\" -DFEAT_MZSCHEME -I "C:\Users\hp\Desktop\racket-x64\include" -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracketxxxxxxx.dll\" -DDYNAMIC_MZGC_DLL=\"libmzgcxxxxxxx.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl526.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /opt:ref /LTCG:STATUS /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:AMD64  msvcrt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python36.lib   "C:\TCL\lib\tclstub86.lib" WSock32.lib .\xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug
```


#### :messages
```
"~\.vim\bundle\jedi-vim\minimal.vimrc" [unix] 59L, 1731C
19 lines yanked
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 20 2018 15:37:12)
  1: ~\_vimrc
  2: ~\.vim\.vimrc
  3: ~\.vim\vimfiles\autoload\plug.vim
  4: C:\Vim\filetype.vim
  5: ~\.vim\bundle\csv.vim\ftdetect\csv.vim
  6: ~\.vim\bundle\rust.vim\ftdetect\rust.vim
  7: ~\.vim\bundle\vim-json\ftdetect\json.vim
  8: ~\.vim\bundle\vim-markdown\ftdetect\markdown.vim
  9: ~\.vim\bundle\vim-obj8\ftdetect\obj8.vim
 10: C:\Vim\menu.vim
 11: C:\Vim\autoload\paste.vim
 12: C:\Vim\ftplugin.vim
 13: C:\Vim\indent.vim
 14: C:\Vim\syntax\syntax.vim
 15: C:\Vim\syntax\synload.vim
 16: C:\Vim\syntax\syncolor.vim
 17: C:\Vim\syntax\nosyntax.vim
 18: ~\.vim\vimfiles\colors\molokai.vim
 19: ~\.vim\bundle\jedi-vim\autoload\jedi.vim
 20: ~\.vim\bundle\ale\plugin\ale.vim
 21: ~\.vim\bundle\ale\autoload\ale\balloon.vim
 22: ~\.vim\bundle\ale\autoload\ale\events.vim
 23: ~\.vim\bundle\csv.vim\plugin\csv.vim
 24: ~\.vim\bundle\dwm.vim\plugin\dwm.vim
 25: ~\.vim\bundle\jedi-vim\plugin\jedi.vim
 26: ~\.vim\bundle\mru\plugin\mru.vim
 27: ~\.vim\bundle\nerdtree\plugin\NERD_tree.vim
 28: ~\.vim\bundle\nerdtree\autoload\nerdtree.vim
 29: ~\.vim\bundle\nerdtree\lib\nerdtree\path.vim
 30: ~\.vim\bundle\nerdtree\lib\nerdtree\menu_controller.vim
 31: ~\.vim\bundle\nerdtree\lib\nerdtree\menu_item.vim
 32: ~\.vim\bundle\nerdtree\lib\nerdtree\key_map.vim
 33: ~\.vim\bundle\nerdtree\lib\nerdtree\bookmark.vim
 34: ~\.vim\bundle\nerdtree\lib\nerdtree\tree_file_node.vim
 35: ~\.vim\bundle\nerdtree\lib\nerdtree\tree_dir_node.vim
 36: ~\.vim\bundle\nerdtree\lib\nerdtree\opener.vim
 37: ~\.vim\bundle\nerdtree\lib\nerdtree\creator.vim
 38: ~\.vim\bundle\nerdtree\lib\nerdtree\flag_set.vim
 39: ~\.vim\bundle\nerdtree\lib\nerdtree\nerdtree.vim
 40: ~\.vim\bundle\nerdtree\lib\nerdtree\ui.vim
 41: ~\.vim\bundle\nerdtree\lib\nerdtree\event.vim
 42: ~\.vim\bundle\nerdtree\lib\nerdtree\notifier.vim
 43: ~\.vim\bundle\nerdtree\autoload\nerdtree\ui_glue.vim
 44: ~\.vim\bundle\nerdtree\nerdtree_plugin\exec_menuitem.vim
 45: ~\.vim\bundle\nerdtree\nerdtree_plugin\fs_menu.vim
 46: ~\.vim\bundle\nerdtree-git-plugin\nerdtree_plugin\git_status.vim
 47: ~\.vim\bundle\rust.vim\plugin\cargo.vim
 48: ~\.vim\bundle\rust.vim\plugin\rust.vim
 49: ~\.vim\bundle\spellrotate.vim\plugin\spellrotate.vim
 50: ~\.vim\bundle\tabline.vim\plugin\tabline.vim
 51: ~\.vim\bundle\tagbar\plugin\tagbar.vim
 52: ~\.vim\bundle\transbuffer.vim\plugin\transbuffer.vim
 53: ~\.vim\bundle\vim-abolish\plugin\abolish.vim
 54: ~\.vim\bundle\vim-airline\plugin\airline.vim
 55: ~\.vim\bundle\vim-airline\autoload\airline\init.vim
 56: ~\.vim\bundle\vim-airline\autoload\airline\parts.vim
 57: ~\.vim\bundle\vim-airline\autoload\airline\util.vim
 58: ~\.vim\bundle\vim-closetag\plugin\closetag.vim
 59: ~\.vim\bundle\vim-diff-enhanced\plugin\EnhancedDiff.vim
 60: ~\.vim\bundle\vim-easy-align\plugin\easy_align.vim
 61: ~\.vim\bundle\vim-easymotion\plugin\EasyMotion.vim
 62: ~\.vim\bundle\vim-game-code-break\plugin\vim-game-code-break.vim
 63: ~\.vim\bundle\vim-grammarous\plugin\grammarous.vim
 64: ~\.vim\bundle\vim-gutentags\plugin\gutentags.vim
 65: ~\.vim\bundle\vim-matchit\plugin\matchit.vim
 66: ~\.vim\bundle\vim-mucomplete\plugin\mucomplete.vim
 67: ~\.vim\bundle\vim-opengrok\plugin\opengrok.vim
 68: ~\.vim\bundle\vim-quickhelp\plugin\quickhelp.vim
 69: ~\.vim\bundle\vim-signature\plugin\signature.vim
 70: ~\.vim\bundle\vim-signature\autoload\signature\utils.vim
 71: ~\.vim\bundle\vim-startify\plugin\startify.vim
 72: ~\.vim\bundle\vim-surround\plugin\surround.vim
 73: ~\.vim\bundle\vim-visual-increment\plugin\visual-increment.vim
 74: C:\Vim\plugin\getscriptPlugin.vim
 75: C:\Vim\plugin\gzip.vim
 76: C:\Vim\plugin\logiPat.vim
 77: C:\Vim\plugin\manpager.vim
```


<details><summary>:scriptnames</summary>


```
  1: ~\_vimrc
  2: ~\.vim\.vimrc
  3: ~\.vim\vimfiles\autoload\plug.vim
  4: C:\Vim\filetype.vim
  5: ~\.vim\bundle\csv.vim\ftdetect\csv.vim
  6: ~\.vim\bundle\rust.vim\ftdetect\rust.vim
  7: ~\.vim\bundle\vim-json\ftdetect\json.vim
  8: ~\.vim\bundle\vim-markdown\ftdetect\markdown.vim
  9: ~\.vim\bundle\vim-obj8\ftdetect\obj8.vim
 10: C:\Vim\menu.vim
 11: C:\Vim\autoload\paste.vim
 12: C:\Vim\ftplugin.vim
 13: C:\Vim\indent.vim
 14: C:\Vim\syntax\syntax.vim
 15: C:\Vim\syntax\synload.vim
 16: C:\Vim\syntax\syncolor.vim
 17: C:\Vim\syntax\nosyntax.vim
 18: ~\.vim\vimfiles\colors\molokai.vim
 19: ~\.vim\bundle\jedi-vim\autoload\jedi.vim
 20: ~\.vim\bundle\ale\plugin\ale.vim
 21: ~\.vim\bundle\ale\autoload\ale\balloon.vim
 22: ~\.vim\bundle\ale\autoload\ale\events.vim
 23: ~\.vim\bundle\csv.vim\plugin\csv.vim
 24: ~\.vim\bundle\dwm.vim\plugin\dwm.vim
 25: ~\.vim\bundle\jedi-vim\plugin\jedi.vim
 26: ~\.vim\bundle\mru\plugin\mru.vim
 27: ~\.vim\bundle\nerdtree\plugin\NERD_tree.vim
 28: ~\.vim\bundle\nerdtree\autoload\nerdtree.vim
 29: ~\.vim\bundle\nerdtree\lib\nerdtree\path.vim
 30: ~\.vim\bundle\nerdtree\lib\nerdtree\menu_controller.vim
 31: ~\.vim\bundle\nerdtree\lib\nerdtree\menu_item.vim
 32: ~\.vim\bundle\nerdtree\lib\nerdtree\key_map.vim
 33: ~\.vim\bundle\nerdtree\lib\nerdtree\bookmark.vim
 34: ~\.vim\bundle\nerdtree\lib\nerdtree\tree_file_node.vim
 35: ~\.vim\bundle\nerdtree\lib\nerdtree\tree_dir_node.vim
 36: ~\.vim\bundle\nerdtree\lib\nerdtree\opener.vim
 37: ~\.vim\bundle\nerdtree\lib\nerdtree\creator.vim
 38: ~\.vim\bundle\nerdtree\lib\nerdtree\flag_set.vim
 39: ~\.vim\bundle\nerdtree\lib\nerdtree\nerdtree.vim
 40: ~\.vim\bundle\nerdtree\lib\nerdtree\ui.vim
 41: ~\.vim\bundle\nerdtree\lib\nerdtree\event.vim
 42: ~\.vim\bundle\nerdtree\lib\nerdtree\notifier.vim
 43: ~\.vim\bundle\nerdtree\autoload\nerdtree\ui_glue.vim
 44: ~\.vim\bundle\nerdtree\nerdtree_plugin\exec_menuitem.vim
 45: ~\.vim\bundle\nerdtree\nerdtree_plugin\fs_menu.vim
 46: ~\.vim\bundle\nerdtree-git-plugin\nerdtree_plugin\git_status.vim
 47: ~\.vim\bundle\rust.vim\plugin\cargo.vim
 48: ~\.vim\bundle\rust.vim\plugin\rust.vim
 49: ~\.vim\bundle\spellrotate.vim\plugin\spellrotate.vim
 50: ~\.vim\bundle\tabline.vim\plugin\tabline.vim
 51: ~\.vim\bundle\tagbar\plugin\tagbar.vim
 52: ~\.vim\bundle\transbuffer.vim\plugin\transbuffer.vim
 53: ~\.vim\bundle\vim-abolish\plugin\abolish.vim
 54: ~\.vim\bundle\vim-airline\plugin\airline.vim
 55: ~\.vim\bundle\vim-airline\autoload\airline\init.vim
 56: ~\.vim\bundle\vim-airline\autoload\airline\parts.vim
 57: ~\.vim\bundle\vim-airline\autoload\airline\util.vim
 58: ~\.vim\bundle\vim-closetag\plugin\closetag.vim
 59: ~\.vim\bundle\vim-diff-enhanced\plugin\EnhancedDiff.vim
 60: ~\.vim\bundle\vim-easy-align\plugin\easy_align.vim
 61: ~\.vim\bundle\vim-easymotion\plugin\EasyMotion.vim
 62: ~\.vim\bundle\vim-game-code-break\plugin\vim-game-code-break.vim
 63: ~\.vim\bundle\vim-grammarous\plugin\grammarous.vim
 64: ~\.vim\bundle\vim-gutentags\plugin\gutentags.vim
 65: ~\.vim\bundle\vim-matchit\plugin\matchit.vim
 66: ~\.vim\bundle\vim-mucomplete\plugin\mucomplete.vim
 67: ~\.vim\bundle\vim-opengrok\plugin\opengrok.vim
 68: ~\.vim\bundle\vim-quickhelp\plugin\quickhelp.vim
 69: ~\.vim\bundle\vim-signature\plugin\signature.vim
 70: ~\.vim\bundle\vim-signature\autoload\signature\utils.vim
 71: ~\.vim\bundle\vim-startify\plugin\startify.vim
 72: ~\.vim\bundle\vim-surround\plugin\surround.vim
 73: ~\.vim\bundle\vim-visual-increment\plugin\visual-increment.vim
 74: C:\Vim\plugin\getscriptPlugin.vim
 75: C:\Vim\plugin\gzip.vim
 76: C:\Vim\plugin\logiPat.vim
 77: C:\Vim\plugin\manpager.vim
 78: C:\Vim\plugin\matchparen.vim
 79: C:\Vim\plugin\netrwPlugin.vim
 80: C:\Vim\plugin\rrhelper.vim
 81: C:\Vim\plugin\spellfile.vim
 82: C:\Vim\plugin\tarPlugin.vim
 83: C:\Vim\plugin\tohtml.vim
 84: C:\Vim\plugin\vimballPlugin.vim
 85: C:\Vim\plugin\zipPlugin.vim
 86: ~\.vim\bundle\vim-signature\after\plugin\signature.vim
 87: ~\.vim\bundle\vim-airline\autoload\airline\extensions.vim
 88: ~\.vim\bundle\vim-airline\autoload\airline\extensions\quickfix.vim
 89: ~\.vim\bundle\vim-airline\autoload\airline.vim
 90: ~\.vim\bundle\vim-airline\autoload\airline\extensions\netrw.vim
 91: ~\.vim\bundle\vim-airline\autoload\airline\extensions\term.vim
 92: ~\.vim\bundle\vim-airline\autoload\airline\extensions\tagbar.vim
 93: ~\.vim\bundle\vim-airline\autoload\airline\extensions\csv.vim
 94: ~\.vim\bundle\vim-airline\autoload\airline\extensions\ale.vim
 95: ~\.vim\bundle\vim-airline\autoload\airline\extensions\whitespace.vim
 96: ~\.vim\bundle\vim-airline\autoload\airline\extensions\po.vim
 97: ~\.vim\bundle\vim-airline\autoload\airline\extensions\wordcount.vim
 98: ~\.vim\bundle\vim-airline\autoload\airline\extensions\tabline.vim
 99: ~\.vim\bundle\vim-airline\autoload\airline\extensions\tabline\autoshow.vim
100: ~\.vim\bundle\vim-airline\autoload\airline\extensions\tabline\tabs.vim
101: ~\.vim\bundle\vim-airline\autoload\airline\extensions\tabline\buffers.vim
102: ~\.vim\bundle\vim-airline\autoload\airline\extensions\gutentags.vim
103: ~\.vim\bundle\vim-airline\autoload\airline\extensions\keymap.vim
104: ~\.vim\bundle\vim-airline\autoload\airline\section.vim
105: ~\.vim\bundle\vim-airline\autoload\airline\highlighter.vim
106: ~\.vim\bundle\vim-airline\autoload\airline\themes\dark.vim
107: ~\.vim\bundle\vim-airline\autoload\airline\themes.vim
108: ~\.vim\bundle\vim-airline\autoload\airline\builder.vim
109: ~\.vim\bundle\vim-airline\autoload\airline\extensions\default.vim
110: C:\Vim\scripts.vim
111: C:\Vim\ftplugin\vim.vim
112: C:\Vim\indent\vim.vim
113: C:\Vim\syntax\vim.vim
114: C:\Vim\syntax\python.vim
115: ~\.vim\bundle\vim-gutentags\autoload\gutentags.vim
116: ~\.vim\bundle\vim-gutentags\autoload\gutentags\ctags.vim
117: ~\.vim\bundle\ale\autoload\ale.vim
118: ~\.vim\bundle\ale\autoload\ale\util.vim
119: ~\.vim\bundle\ale\autoload\ale\linter.vim
120: ~\.vim\bundle\ale\ale_linters\vim\ale_custom_linting_rules.vim
121: ~\.vim\bundle\ale\ale_linters\vim\vint.vim
122: ~\.vim\bundle\ale\autoload\ale\engine.vim
123: ~\.vim\bundle\ale\autoload\ale\history.vim
124: ~\.vim\bundle\ale\autoload\ale\sign.vim
125: ~\.vim\bundle\ale\autoload\ale\list.vim
126: ~\.vim\bundle\ale\autoload\ale\highlight.vim
127: ~\.vim\bundle\ale\autoload\ale\cursor.vim
128: ~\.vim\bundle\vim-signature\autoload\signature\sign.vim
129: ~\.vim\bundle\vim-signature\autoload\signature\mark.vim
130: ~\.vim\bundle\vim-airline\autoload\airline\extensions\tabline\ctrlspace.vim
131: ~\.vim\bundle\vim-airline\autoload\airline\extensions\tabline\builder.vim
132: ~\.vim\bundle\vim-airline\autoload\airline\extensions\tabline\buflist.vim
133: ~\.vim\bundle\vim-airline\autoload\airline\extensions\tabline\formatters\default.vim
134: ~\.vim\bundle\tagbar\autoload\tagbar.vim
135: ~\.vim\bundle\tagbar\autoload\tagbar\debug.vim
136: ~\.vim\bundle\tagbar\autoload\tagbar\types\uctags.vim
137: ~\.vim\bundle\tagbar\autoload\tagbar\prototypes\typeinfo.vim
138: ~\.vim\bundle\tagbar\autoload\tagbar\prototypes\fileinfo.vim
139: ~\.vim\bundle\tagbar\autoload\tagbar\prototypes\normaltag.vim
140: ~\.vim\bundle\tagbar\autoload\tagbar\prototypes\basetag.vim
141: ~\.vim\bundle\tagbar\autoload\tagbar\prototypes\kindheadertag.vim
142: ~\.vim\bundle\tagbar\autoload\tagbar\sorting.vim
143: ~\.vim\bundle\tagbar\autoload\tagbar\state.vim
144: ~\.vim\bundle\ale\autoload\ale\statusline.vim
145: ~\.vim\bundle\ale\autoload\ale\hover.vim
```
</details>

**Comment by blueyed** [comment] 2018-10-24 20:08
Duplicate of https://github.com/davidhalter/jedi-vim/issues/870.

**Closed by blueyed** 2018-10-24 20:08 UTC
