### ISSUE TITLE
After exiting vim bash prompt appears at the bottom of screen due to jedi-vim plugin

### ISSUE THREAD

**Issue by rayanshuman** [davidhalter/jedi-vim#729] opened 2017-08-07 14:21 UTC
### Steps to reproduce
0. clear <enter> (to clear screen)
1. do a ls
2. open vim
3. exit vim
4. the bash prompt/cursor is not continued from the o/p of ls command, instead it moves to the bottom

same as above
### Output of “:verbose JediDebugInfo”

You should run this in a buffer with filetype "python".
#### Jedi-vim debug information
Using Python version: 2
 - sys.version: `2.7.12 (default, Nov 19 2016, 06:48:10), [GCC 5.4.0 20160609]`
 - site module: `/usr/lib/python2.7/site.pyc`
Jedi path: `/home/ary/.vim/bundle/jedi-vim/jedi/jedi/__init__.py`
 - version: 0.10.2
 - sys_path:
    - `/home/ary/.vim/bundle/jedi-vim`
    - `/usr/lib/python2.7`
    - `/usr/lib/python2.7/plat-x86_64-linux-gnu`
    - `/usr/lib/python2.7/lib-tk`
    - `/usr/lib/python2.7/lib-old`
    - `/usr/lib/python2.7/lib-dynload`
    - `/usr/local/lib/python2.7/dist-packages`
    - `/usr/lib/python2.7/dist-packages`
    - `/usr/lib/python2.7/dist-packages/PILcompat`
    - `/usr/lib/python2.7/dist-packages/gtk-2.0`
    - `_vim_path_`
    - `/home/ary/.vim/bundle/vim-virtualenv/autoload`
 - jedi-vim git version: 0.8.0-89-ga2cf229
 - jedi git submodule status:  5427b02712828b2875d35b5ee1c8b5e58f820537 jedi (v0.10.2)

##### Settings
```
g:jedi#usages_command = '<leader>z' (default: '<leader>n')


  omnifunc=
  completeopt=menuone,longest,preview
        Last set from ~/.vim/bundle/jedi-vim/plugin/jedi.vim
```

#### :version
```

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug  5 2017 17:39:45)
Included patches: 1-862
Compiled by ary
Huge version without GUI.  Features included (+) or not (-):
+acl             +comments        +extra_search    +keymap          +mouse_dec       +path_extra      +smartindent     +timers          +X11
+arabic          +conceal         +farsi           +lambda          -mouse_gpm       -perl            +startuptime     +title           +xfontset
+autocmd         +cryptv          +file_in_path    +langmap         -mouse_jsbterm   +persistent_undo +statusline      -toolbar         -xim
-balloon_eval    +cscope          +find_in_path    +libcall         +mouse_netterm   +postscript      -sun_workshop    +user_commands   +xpm
-browse          +cursorbind      +float           +linebreak       +mouse_sgr       +printer         +syntax          +vertsplit       +xsmp_interact
++builtin_terms  +cursorshape     +folding         +lispindent      -mouse_sysmouse  +profile         +tag_binary      +virtualedit     +xterm_clipboard
+byte_offset     +dialog_con      -footer          +listcmds        +mouse_urxvt     +python          +tag_old_static  +visual          -xterm_save
+channel         +diff            +fork()          +localmap        +mouse_xterm     -python3         -tag_any_white   +visualextra
+cindent         +digraphs        -gettext         -lua             +multi_byte      +quickfix        -tcl             +viminfo
+clientserver    -dnd             -hangul_input    +menu            +multi_lang      +reltime         +termguicolors   +vreplace
+clipboard       -ebcdic          +iconv           +mksession       -mzscheme        +rightleft       -terminal        +wildignore
+cmdline_compl   +emacs_tags      +insert_expand   +modify_fname    +netbeans_intg   -ruby            +terminfo        +wildmenu
+cmdline_hist    +eval            +job             +mouse           +num64           +scrollbind      +termresponse    +windows
+cmdline_info    +ex_extra        +jumplist        -mouseshape      +packages        +signs           +textobjects     +writebackup
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug  5 2017 17:39:45)
  1: ~/.vimrc
  2: /usr/share/vim/vim80/ftoff.vim
  3: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
  4: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
  5: /usr/share/vim/vim80/filetype.vim
  6: /usr/share/vim/vim80/ftplugin.vim
  7: /usr/share/vim/vim80/indent.vim
  8: /usr/share/vim/vim80/syntax/syntax.vim
  9: /usr/share/vim/vim80/syntax/synload.vim
 10: /usr/share/vim/vim80/syntax/syncolor.vim
 11: ~/.vim/bundle/gruvbox/colors/gruvbox.vim
 12: ~/.vim/bundle/vim-colors-solarized/autoload/togglebg.vim
 13: ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim
 14: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 15: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 16: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 17: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 18: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 19: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 20: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 21: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 22: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 23: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 24: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 25: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 26: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 27: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 28: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 29: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 30: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 31: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 32: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 33: ~/.vim/bundle/vim-nerdtree-tabs/nerdtree_plugin/vim-nerdtree-tabs.vim
 34: ~/.vim/bundle/ctrlp.vim/plugin/ctrlp.vim
 35: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/mrufiles.vim
 36: ~/.vim/bundle/ack.vim/plugin/ack.vim
 37: ~/.vim/bundle/vim-bufferline/plugin/bufferline.vim
 38: ~/.vim/bundle/vim-bufferline/autoload/bufferline.vim
 39: ~/.vim/bundle/vim-surround/plugin/surround.vim
 40: ~/.vim/bundle/ale/plugin/ale.vim
 41: ~/.vim/bundle/ale/autoload/ale.vim
 42: ~/.vim/bundle/vim-virtualenv/plugin/virtualenv.vim
 43: ~/.vim/bundle/vim-virtualenv/autoload/virtualenv.vim
 44: ~/.vim/bundle/supertab/plugin/supertab.vim
 45: ~/.vim/bundle/tagbar/plugin/tagbar.vim
 46: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 47: ~/.vim/bundle/SimpylFold/plugin/SimpylFold.vim
 48: ~/.vim/bundle/vim-airline/plugin/airline.vim
 49: ~/.vim/bundle/vim-airline/autoload/airline.vim
 50: ~/.vim/bundle/vim-airline/autoload/airline/init.vim
 51: ~/.vim/bundle/vim-airline/autoload/airline/parts.vim
 52: ~/.vim/bundle/vim-airline-themes/plugin/airline-themes.vim
 53: ~/.vim/bundle/nerdcommenter/plugin/NERD_commenter.vim
 54: /usr/share/vim/vim80/plugin/getscriptPlugin.vim
 55: /usr/share/vim/vim80/plugin/gzip.vim
 56: /usr/share/vim/vim80/plugin/logiPat.vim
 57: /usr/share/vim/vim80/plugin/manpager.vim
 58: /usr/share/vim/vim80/plugin/matchparen.vim
 59: /usr/share/vim/vim80/plugin/netrwPlugin.vim
 60: /usr/share/vim/vim80/plugin/rrhelper.vim
 61: /usr/share/vim/vim80/plugin/spellfile.vim
 62: /usr/share/vim/vim80/plugin/tarPlugin.vim
 63: /usr/share/vim/vim80/plugin/tohtml.vim
 64: /usr/share/vim/vim80/plugin/vimballPlugin.vim
 65: /usr/share/vim/vim80/plugin/zipPlugin.vim
 66: ~/.vim/bundle/ale/after/plugin/ale.vim
 67: ~/.vim/bundle/ale/autoload/ale/util.vim
 68: ~/.vim/bundle/ale/autoload/ale/linter.vim
 69: ~/.vim/bundle/vim-airline/autoload/airline/extensions.vim
 70: ~/.vim/bundle/vim-airline/autoload/airline/extensions/quickfix.vim
 71: ~/.vim/bundle/vim-airline/autoload/airline/extensions/netrw.vim
 72: ~/.vim/bundle/vim-airline/autoload/airline/extensions/ctrlp.vim
 73: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tagbar.vim
 74: ~/.vim/bundle/vim-airline/autoload/airline/extensions/branch.vim
 75: ~/.vim/bundle/vim-airline/autoload/airline/extensions/bufferline.vim
 76: ~/.vim/bundle/vim-airline/autoload/airline/extensions/virtualenv.vim
 77: ~/.vim/bundle/vim-airline/autoload/airline/extensions/ale.vim
 78: ~/.vim/bundle/vim-airline/autoload/airline/extensions/whitespace.vim
 79: ~/.vim/bundle/vim-airline/autoload/airline/extensions/wordcount.vim
 80: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline.vim
 81: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/autoshow.vim
 82: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/tabs.vim
 83: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buffers.vim
 84: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/ctrlspace.vim
 85: ~/.vim/bundle/vim-airline/autoload/airline/section.vim
 86: ~/.vim/bundle/vim-airline/autoload/airline/highlighter.vim
 87: ~/.vim/bundle/vim-airline-themes/autoload/airline/themes/understated.vim
 88: ~/.vim/bundle/vim-airline/autoload/airline/themes.vim
 89: ~/.vim/bundle/vim-airline/autoload/airline/util.vim
 90: ~/.vim/bundle/vim-airline/autoload/airline/builder.vim
 91: ~/.vim/bundle/vim-airline/autoload/airline/extensions/default.vim
 92: ~/.vim/bundle/ale/autoload/ale/events.vim
 93: ~/.vim/bundle/ale/autoload/ale/cursor.vim
 94: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buflist.vim
 95: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/formatters/default.vim
 96: ~/.vim/bundle/tagbar/autoload/tagbar.vim
 97: ~/.vim/bundle/ale/autoload/ale/statusline.vim
 98: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug  5 2017 17:39:45)
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug  5 2017 17:39:45)


1 line less; before #1  1 seconds ago
```

<details><summary>:scriptnames</summary>

```
  1: ~/.vimrc
  2: /usr/share/vim/vim80/ftoff.vim
  3: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
  4: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
  5: /usr/share/vim/vim80/filetype.vim
  6: /usr/share/vim/vim80/ftplugin.vim
  7: /usr/share/vim/vim80/indent.vim
  8: /usr/share/vim/vim80/syntax/syntax.vim
  9: /usr/share/vim/vim80/syntax/synload.vim
 10: /usr/share/vim/vim80/syntax/syncolor.vim
 11: ~/.vim/bundle/gruvbox/colors/gruvbox.vim
 12: ~/.vim/bundle/vim-colors-solarized/autoload/togglebg.vim
 13: ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim
 14: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 15: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 16: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 17: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 18: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 19: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 20: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 21: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 22: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 23: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 24: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 25: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 26: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 27: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 28: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 29: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 30: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 31: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 32: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 33: ~/.vim/bundle/vim-nerdtree-tabs/nerdtree_plugin/vim-nerdtree-tabs.vim
 34: ~/.vim/bundle/ctrlp.vim/plugin/ctrlp.vim
 35: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/mrufiles.vim
 36: ~/.vim/bundle/ack.vim/plugin/ack.vim
 37: ~/.vim/bundle/vim-bufferline/plugin/bufferline.vim
 38: ~/.vim/bundle/vim-bufferline/autoload/bufferline.vim
 39: ~/.vim/bundle/vim-surround/plugin/surround.vim
 40: ~/.vim/bundle/ale/plugin/ale.vim
 41: ~/.vim/bundle/ale/autoload/ale.vim
 42: ~/.vim/bundle/vim-virtualenv/plugin/virtualenv.vim
 43: ~/.vim/bundle/vim-virtualenv/autoload/virtualenv.vim
 44: ~/.vim/bundle/supertab/plugin/supertab.vim
 45: ~/.vim/bundle/tagbar/plugin/tagbar.vim
 46: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 47: ~/.vim/bundle/SimpylFold/plugin/SimpylFold.vim
 48: ~/.vim/bundle/vim-airline/plugin/airline.vim
 49: ~/.vim/bundle/vim-airline/autoload/airline.vim
 50: ~/.vim/bundle/vim-airline/autoload/airline/init.vim
 51: ~/.vim/bundle/vim-airline/autoload/airline/parts.vim
 52: ~/.vim/bundle/vim-airline-themes/plugin/airline-themes.vim
 53: ~/.vim/bundle/nerdcommenter/plugin/NERD_commenter.vim
 54: /usr/share/vim/vim80/plugin/getscriptPlugin.vim
 55: /usr/share/vim/vim80/plugin/gzip.vim
 56: /usr/share/vim/vim80/plugin/logiPat.vim
 57: /usr/share/vim/vim80/plugin/manpager.vim
 58: /usr/share/vim/vim80/plugin/matchparen.vim
 59: /usr/share/vim/vim80/plugin/netrwPlugin.vim
 60: /usr/share/vim/vim80/plugin/rrhelper.vim
 61: /usr/share/vim/vim80/plugin/spellfile.vim
 62: /usr/share/vim/vim80/plugin/tarPlugin.vim
 63: /usr/share/vim/vim80/plugin/tohtml.vim
 64: /usr/share/vim/vim80/plugin/vimballPlugin.vim
 65: /usr/share/vim/vim80/plugin/zipPlugin.vim
 66: ~/.vim/bundle/ale/after/plugin/ale.vim
 67: ~/.vim/bundle/ale/autoload/ale/util.vim
 68: ~/.vim/bundle/ale/autoload/ale/linter.vim
 69: ~/.vim/bundle/vim-airline/autoload/airline/extensions.vim
 70: ~/.vim/bundle/vim-airline/autoload/airline/extensions/quickfix.vim
 71: ~/.vim/bundle/vim-airline/autoload/airline/extensions/netrw.vim
 72: ~/.vim/bundle/vim-airline/autoload/airline/extensions/ctrlp.vim
 73: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tagbar.vim
 74: ~/.vim/bundle/vim-airline/autoload/airline/extensions/branch.vim
 75: ~/.vim/bundle/vim-airline/autoload/airline/extensions/bufferline.vim
 76: ~/.vim/bundle/vim-airline/autoload/airline/extensions/virtualenv.vim
 77: ~/.vim/bundle/vim-airline/autoload/airline/extensions/ale.vim
 78: ~/.vim/bundle/vim-airline/autoload/airline/extensions/whitespace.vim
 79: ~/.vim/bundle/vim-airline/autoload/airline/extensions/wordcount.vim
 80: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline.vim
 81: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/autoshow.vim
 82: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/tabs.vim
 83: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buffers.vim
 84: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/ctrlspace.vim
 85: ~/.vim/bundle/vim-airline/autoload/airline/section.vim
 86: ~/.vim/bundle/vim-airline/autoload/airline/highlighter.vim
 87: ~/.vim/bundle/vim-airline-themes/autoload/airline/themes/understated.vim
 88: ~/.vim/bundle/vim-airline/autoload/airline/themes.vim
 89: ~/.vim/bundle/vim-airline/autoload/airline/util.vim
 90: ~/.vim/bundle/vim-airline/autoload/airline/builder.vim
 91: ~/.vim/bundle/vim-airline/autoload/airline/extensions/default.vim
 92: ~/.vim/bundle/ale/autoload/ale/events.vim
 93: ~/.vim/bundle/ale/autoload/ale/cursor.vim
 94: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buflist.vim
 95: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/formatters/default.vim
 96: ~/.vim/bundle/tagbar/autoload/tagbar.vim
 97: ~/.vim/bundle/ale/autoload/ale/statusline.vim
 98: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
```
</details>

**Comment by blueyed** [comment] 2017-08-07 17:52
Duplicate of https://github.com/davidhalter/jedi-vim/issues/721?

**Closed** 2017-08-07 18:34 UTC

**Comment by rayanshuman** [comment] 2017-08-07 18:55
It's fixed. Thanks!
