### ISSUE TITLE
completeopt always gets overwritten

### ISSUE THREAD

**Issue by wzyboy** [davidhalter/jedi-vim#374] opened 2015-03-18 12:52 UTC
Hi David,

thanks for your great work!

I may find a little bug in jedi-vim. In ```README.rst``` you suggest that setting ```autocmd FileType python setlocal completeopt-=preview``` in ```~/.vimrc``` will disable the preview window. But this is not working for me.

After I added that line to my ```~/.vimrc```, I'm still getting annoying (for me, sorry) preview window when editing a python script. ```:verbose set completeopt``` returns:

      completeopt=menuone,longest,preview
        Last set from /usr/share/vim/vimfiles/ftplugin/python/jedi.vim

So my setting of ```completeopt``` in ```~/.vimrc``` is getting overwritten by ```jedi.vim```, and ```:scriptnames``` confirms my guess.

I find the option is getting set here: https://github.com/davidhalter/jedi-vim/blob/master/ftplugin/python/jedi.vim#L42-L43

So I added another line of ```let g:jedi#auto_vim_configuration = 0``` in ```~/.vimrc``` and ```completeopt``` does not get overwritten any more.

Is this a bug or is this by design? I guess this only occurs when people install jedi.vim in system directory.

**Comment by davidhalter** [comment] 2015-03-22 12:02
Hi Zhuoyun

This is by design. However, you're absolutely right, that changing the completeopt may not make sense and the documentation needs to be corrected.

If you want to modify it, you need to either `let g:jedi#auto_vim_configuration = 0` or modify it **after** Jedi has loaded. (Typically you invoke the plugins with pathogen, vundle, etc. After that you can just change the setting).

**Comment by wzyboy** [comment] 2015-03-23 09:49
> If you want to modify it, you need to either let g:jedi#auto_vim_configuration = 0 or modify it after Jedi has loaded.

The later approach is not available for me since I installed vim-jedi via system package manager and vimfiles in  ```/usr/share/vim/``` is always loaded at last.

I'll do with the former approach :-)

**Comment by davidhalter** [comment] 2015-03-23 15:38
I'm still going to reopen, because we should actually improve the documentation there.

**Comment by blueyed** [comment] 2015-04-29 22:04
It seems like autocommands for filetypes from ~/.vimrc (the `autocmd FileType python setlocal completeopt-=preview`) is being executed before filetype plugins.
You would have to put this into ~/.vim/after/ftplugin/python.vim (`setlocal completeopt-=preview`) - that's what the docs should then currently mention.

What do you think about only configuring/changing it when the user uses the default setting for `complete`? (can be retrieved via `:let save=&complete | set complete& | let default=&complete | let &complete=default`)

Another idea would be to set the default for `g:jedi#auto_vim_configuration` to 0 (which I am using myself).

**Comment by davidhalter** [comment] 2015-04-29 23:12
I agree with the default idea. That will remove solve most cases.

I'm against changing the default for `auto_vim_configuration`. It solves me a lot of trouble when people are using jedi-vim that have no VIM knowledge (less jedi-vim is not working mails).

**Comment by blueyed** [comment] 2015-04-30 00:37
> I agree with the default idea. That will remove solve most cases.

Ok, however there are other plugins that change the default (e.g. YouCompleteMe), and then Jedi would not re-change it.  So this might cause regressions in some cases.

However, the `completeopt` setting is global, and therefore should maybe get moved out of the ftplugin to the plugin. This would allow to override it more easily, e.g. like mentioned in the docs.

**Comment by davidhalter** [comment] 2015-04-30 01:03
I'm ok with that.

**Comment by davidhalter** [comment] 2015-04-30 01:04
Except we don't know auto_vim_conf by that time?

**Comment by blueyed** [comment] 2015-04-30 01:07
It's being used there already - see #398.

**Comment by blueyed** [comment] 2015-05-01 04:01
Should be fixed now via https://github.com/davidhalter/jedi-vim/commit/83d398bc5df476b6750973794e4776fb25770574.

**Closed by blueyed** 2015-05-01 04:01 UTC
Labels: bug

**Comment by davidhalter** [comment] 2015-05-03 01:39
Thanks!
