### ISSUE TITLE
show attribute slow or "pattern not found", when the variable is "not explicitly declared"

### ISSUE THREAD

**Issue by frankyan** [davidhalter/jedi-vim#292] opened 2014-07-23 09:04 UTC
Although "not explicitly declared" is not an exact way to illustrate the issue, it's an easy way to understand. For example:
```
import pandas as pd
target = pd.read_csv( "test.csv" )
target.
```
It took more than 4 seconds to show the attribute list of `target`. If `target` is explicitly declared as `pd.DataFrame`, then everything is ok. For example
```
data = {                 
            'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],   
           'year': [2000, 2001, 2002, 2001, 2002], 
           'pop': [1.5, 1.7, 3.6, 2.4, 2.9] 
           }      
frame = pd.DataFrame(data)
frame.
```  
It shows the attribute list of `frame` immediately and without any delay.

So it seems that the type inference of jedi-vim caused the problem. Then I test another situation.
```
import sys
for line in sys.stdin:
    line.
```
It reported  `Omni completion (^O^N^P) Pattern not found` .  It indicates that jedi-vim cannot inference the type of  `line`. 

Jedi-vim is a good and powerful plugin, only this issue bothers me. I don't know much about the mechanism of jedi-vim, so I don't know whether this issue can be fixed. I need your help.

I am using Ubuntu 12.04, vim 7.4, jedi  0.8.1-final0, python 2.7.3. jedi-vim is installed by Vundle.

**Comment by davidhalter** [comment] 2015-03-31 00:02
Since this is a Jedi issue and at least one issue exists in the Jedi tracker (https://github.com/davidhalter/jedi/issues/520) that mirrors your concerns, I'm closing this one.

You're BTW absolutely right that the problem is Jedi's inference. It's hard to infer certain functions in Python, because of Python's dynamic nature. So sometimes Jedi stops and ignores constructs.

**Closed by davidhalter** 2015-03-31 00:02 UTC
Labels: jedi-issue
