### ISSUE TITLE
show call signatures in command line not work in mvim(gui vim)

### ISSUE THREAD

**Issue by aliev** [davidhalter/jedi-vim#345] opened 2015-01-03 16:25 UTC
I also think it would be good to add to the documentation information that this option will only work if the showmode option is disabled.

https://dl.dropboxusercontent.com/u/5837324/jedi-vim.png

**Comment by davidhalter** [comment] 2015-01-05 00:17
@wilywampa Do you agree?

**Comment by wilywampa** [comment] 2015-01-05 04:00
My laptop is restoring from Time Machine at the moment so I can't test MacVim specifically yet, but the signatures work in Cygwin gVim:
![gvim_callsigs](https://cloud.githubusercontent.com/assets/4472522/5608905/b48ba9f2-944e-11e4-8e1b-c2de3fca1c44.png)

However, when I went to test it I found there was a change in NeoComplete that causes the call signatures to disappear. For omni completion, NeoComplete now calls the omnifunction with `findstart = 1` in `neocomplete#handler#_do_auto_complete()`, and `clear_call_signatures()` is called right at the start of Jedi's omnifunction. NeoComplete effectively clears the call signatures at every `InsertCharPre`/`CursorMovedI`/TextChangedI`.

I traced the `clear_call_signatures()` in Jedi's completion function  back to https://github.com/davidhalter/jedi-vim/commit/48ab6c613fa985c2dacd502ee510cee89ea88502. The call signatures don't need to be cleared at all for the command line call signatures. However, they need to be cleared for the regular call signatures so the call signature isn't interpreted as text to be completed. I propose moving `clear_call_signatures()` after the `findstart` section of the completion function. If that will still cause the problems addressed by https://github.com/davidhalter/jedi-vim/commit/48ab6c613fa985c2dacd502ee510cee89ea88502 we'll need to collaborate with @Shougo to work something out.

For now, I put PRs in for the documentation: https://github.com/davidhalter/jedi-vim/pull/346
and for the NeoComplete issue with command line call signatures: https://github.com/davidhalter/jedi-vim/pull/347

**Comment by wilywampa** [comment] 2015-01-05 07:22
I was able to reproduce the issue in MacVim. The call signatures work if anything is typed after the opening parenthesis but not with just the parenthesis. I thought maybe it had to do with the highlighting of match parentheses. Sure enough, adding `let loaded_matchparen = 1` solved the problem. I'll have to look into the matchparen plugin and see what's different for MacVim.

**Comment by wilywampa** [comment] 2015-01-05 07:50
Here's the problem. If `getcurpos()` isn't available (because it was introduced in Vim 7.4.313, which is not in the latest MacVim), matchparen uses `winsaveview()` instead of `getcurpos()`. I have no clue why `winsaveview()` was used instead of `getpos('.')`, but using `winsaveview()/winrestview()` apparently redraws the command line.

Disabling matchparen fixes the problem but obviously at the cost of some functionality. I would recommend replacing the matchparen.vim in Vim's share/runtime path with a version that uses `getpos('.')` instead of `winsaveview()`.

Here is a patched version as well as the patch itself (at the bottom after the patched version): https://gist.github.com/wilywampa/eeb0fb8f3f247c34a70c

**Comment by davidhalter** [comment] 2015-01-05 10:16
> Disabling matchparen fixes the problem but obviously at the cost of some functionality. I would recommend replacing the matchparen.vim in Vim's share/runtime path with a version that uses getpos('.') instead of winsaveview().

And how would we accomplish that?

**Comment by wilywampa** [comment] 2015-01-06 02:13
Yeah, I can't think of any way to fix it without modifying matchparen.vim (as opposed to changing some settings or re-ordering autocmds, which I haven't had any success with). Maybe write a little script to generate a patched version in the user's plugin directory.

Slightly better than disabling matchparen completely is to disable it in insert mode with:
```vim
autocmd! matchparen CursorMovedI
autocmd! matchparen TextChangedI
```
It might be possible to disable and re-enable matchparen's autocmds but not in any way that's obvious to me.

**Comment by davidhalter** [comment] 2015-01-06 09:24
I think your approach is fine. Just replace it. Maybe post your findings on VIMs mailing list, but then again the problem only affects the old versions, so I guess we're good in the future.

**Comment by davidhalter** [comment] 2015-03-25 13:17
Can we close this one?

**Comment by aliev** [comment] 2015-03-25 13:34
@davidhalter I think you can close. it is desirable to make a note in the documentation

**Comment by davidhalter** [comment] 2015-03-25 13:35
What note?

**Comment by davidhalter** [comment] 2015-03-25 13:35
You're very welcome to do a PR :)

**Comment by aliev** [comment] 2015-03-25 13:38
@davidhalter after turning off matchparen this feature works stable

**Closed** 2015-03-25 14:00 UTC
