### ISSUE TITLE
vim hangs

### ISSUE THREAD

**Issue by petergthatsme** [davidhalter/jedi-vim#537] opened 2016-01-27 18:24 UTC
my installation of jedi-vim works on some packages (i.e i can do ctrl+space and see completion options), but in one case (that i've found so far) completely hangs vim. So in particular i write this code

```
import qutip as q
```

then run 

```
q.
```

after a couple of seconds, vim will start to spit out errors (see attached image). If i click within the vim window after that vim hangs and i have to kill it with -9. Any ideas? I'm on ubuntu 14.04 and I've tried this with the latest vim-jedi.

thanks
![screenshot_1](https://cloud.githubusercontent.com/assets/4156234/12623637/affc963e-c4f0-11e5-9dbd-c591b45fff11.png)

Some info:
$ uname -a
Linux desktop6 3.19.0-39-generic #44~14.04.1-Ubuntu SMP Wed Dec 2 10:00:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ git log | head -8
commit 625c568b1249db8c5f1b06a1f9371c06ba2d08b5
Merge: dc23f0b 8215b22
Author: Dave Halter davidhalter88@gmail.com
Date:   Thu Jan 14 14:14:44 2016 +0100

```
Merge pull request #527 from prologic/master

Fixes Python 2.6 compatibility issues with `str.format()`
```

:ver
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:59)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +clipboard       +cursorshape     +extra_search    -hangul_input    +listcmds        +mouse_gpm       -mzscheme        -python3         +startuptime     +termresponse    +viminfo         +xsmp_interact
+arabic          +cmdline_compl   +dialog_con_gui  +farsi           +iconv           +localmap        -mouse_jsbterm   +netbeans_intg   +quickfix        +statusline      +textobjects     +vreplace        +xterm_clipboard
+autocmd         +cmdline_hist    +diff            +file_in_path    +insert_expand   +lua             +mouse_netterm   +path_extra      +reltime         -sun_workshop    +title           +wildignore      -xterm_save
+balloon_eval    +cmdline_info    +digraphs        +find_in_path    +jumplist        +menu            +mouse_sgr       +perl            +rightleft       +syntax          +toolbar         +wildmenu        +xpm
+browse          +comments        +dnd             +float           +keymap          +mksession       -mouse_sysmouse  +persistent_undo +ruby            +tag_binary      +user_commands   +windows
++builtin_terms  +conceal         -ebcdic          +folding         +langmap         +modify_fname    +mouse_urxvt     +postscript      +scrollbind      +tag_old_static  +vertsplit       +writebackup
+byte_offset     +cryptv          +emacs_tags      -footer          +libcall         +mouse           +mouse_xterm     +printer         +signs           -tag_any_white   +virtualedit     +X11
+cindent         +cscope          +eval            +fork()          +linebreak       +mouseshape      +multi_byte      +profile         +smartindent     +tcl             +visual          -xfontset
+clientserver    +cursorbind      +ex_extra        +gettext         +lispindent      +mouse_dec       +multi_lang      +python          -sniff           +terminfo        +visualextra     +xim
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1
.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -fstack-protector --param=s
sp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.
0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protect
or -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x8
6_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib

**Comment by davidhalter** [comment] 2016-01-27 18:32
Is there a way we can get the whole error message?

It looks like some libraries are printing to stdout when imported by Jedi (builtins). This shouldn't be the case, we should probably catch that.

**Comment by petergthatsme** [comment] 2016-01-27 18:42
so the messages are shown in the image (to get each new line, I click "enter", or to get the whole thing I press ":")... as vim hangs right after, I can't grab the messages with ":mes". Any other way you suggest I grab more info?
thanks

**Comment by davidhalter** [comment] 2016-01-27 19:01
Oh, I think I know the problem. You cannot really fetch them all. It's ok. Let's just ignore it for now.

**Comment by petergthatsme** [comment] 2016-01-28 16:36
you mean ignore the messages or the problem? ;)

**Comment by davidhalter** [comment] 2016-07-21 21:47
Can you retry on the latest Jedi dev branch?

**Comment by petergthatsme** [comment] 2016-07-25 15:29
i still see the same issue with the latest... BUT it only seems to happen with one module (qutip), and with others (at least the few i've tried) jedi-vim seems to work fine and does not hang.

**Comment by Griatch** [comment] 2017-10-24 12:45
I now see the freeze issue consistently with the `pudb` debugger module and latest git version of `jedi-vim`. 
```
import pudb
pudb.
```
Total freeze every time. Killing vim with `-9` required to recover.

**Comment by blueyed** [comment] 2017-10-24 20:46
Cannot reproduce on master nor the update-parso branch.
But I use <kbd>Ctrl-X</kbd> <kbd>Ctrl-o</kbd> to trigger jedi-vim manually.
It shows me `pudb.absolute_import` etc.

**Comment by blueyed** [comment] 2017-10-24 20:47
@Griatch 
Please create a new issue.

**Comment by blueyed** [comment] 2017-10-24 20:48
@petergthatsme 
You can get the message history with `:messages` in Vim.

I assume that it is not an issue anymore, and close it therefore.
Please re-open if that is not the case and you can provide more info.

**Closed by blueyed** 2017-10-24 20:48 UTC
Labels: jedi-issue
