### ISSUE TITLE
Docstring popup being written to doc

### ISSUE THREAD

**Issue by chppppp** [davidhalter/jedi-vim#645] opened 2016-12-08 19:40 UTC
### Issue
the docstring popup from Jedi-vim gets written to my doc instead of just popping up and disappearing.
### Steps to reproduce
do anything to cause the docstring to display
### Versions

 - jedi-vim: latest as of this post
 - Vim / Neovim: 
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 17 2016 06:26:47)
    Included patches: 1-488, 576
    Extra patches: 8.0.0056
 - Python: Python 2.7.9
    

In case you are not using jedi-vim from Git master, please test it there, too.

### Output of the "JediDebugInfo" command (in a Python buffer)

Using Python version: 2                                                                                            
 - sys.version: 2.7.9 (default, Jun 29 2016, 13:11:10), [GCC 4.9.2]
 - site module: /usr/lib/python2.7/site.pyc
Jedi path: /home/carrier/.vim/bundle/jedi-vim/jedi/jedi/__init__.pyc
Jedi version: 0.10.0
jedi-vim git version: 0.8.0-54-g671f9f5
jedi git submodule status:  2ba78ab725f1e02dfef8bc50b0204cf656e8ee23 jedi (v0.9.0-547-g2ba78ab)

### Output of the "messages" Vim command

  Messages maintainer: Bram Moolenaar   <Bram@vim.org>                                                                 

### Output of "scriptnames" Vim command

  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim74/debian.vim
  3: ~/.vimrc
  4: ~/.vim/autoload/pathogen.vim
  5: /usr/share/vim/vim74/syntax/syntax.vim
  6: /usr/share/vim/vim74/syntax/synload.vim
  7: /usr/share/vim/vim74/syntax/syncolor.vim
  8: /usr/share/vim/vim74/filetype.vim
  9: /usr/share/vim/vim74/ftplugin.vim
 10: /usr/share/vim/vim74/indent.vim
 11: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 12: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 13: /usr/share/vim/vim74/plugin/gzip.vim
 14: /usr/share/vim/vim74/plugin/matchparen.vim
 15: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 16: /usr/share/vim/vim74/plugin/rrhelper.vim
 17: /usr/share/vim/vim74/plugin/spellfile.vim
 18: /usr/share/vim/vim74/plugin/tarPlugin.vim
 19: /usr/share/vim/vim74/plugin/tohtml.vim
 20: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 21: /usr/share/vim/vim74/plugin/zipPlugin.vim
 22: /usr/share/vim/vim74/syntax/python.vim
 23: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 24: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 25: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 26: /usr/share/vim/vim74/ftplugin/python.vim
 27: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 28: /usr/share/vim/vim74/indent/python.vim
Press ENTER or type command to continue

**Comment by chris-johnson-tl** [comment] 2016-12-08 20:25
Same issue for me using the following vim version:

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 15 2016 18:04:06)
Included patches: 1-86
Python: Python 2.7.12

JediDebugInfo
Using Python version: 2
 - sys.version: 2.7.12 (default, Nov  7 2016, 11:55:55), [GCC 6.2.1 20160830]
 - site module: /usr/lib/python2.7/site.pyc
Jedi path: /home/chris/.vim/plugged/jedi-vim/jedi/jedi/__init__.pyc
Jedi version: 0.10.0
jedi-vim git version: 671f9f5
jedi git submodule status:  2ba78ab725f1e02dfef8bc50b0204cf656e8ee23 jedi (v0.9.0-547-g2ba78ab)

**Comment by chris-johnson-tl** [comment] 2016-12-08 20:34
Seems to be related to https://github.com/davidhalter/jedi-vim/issues/641 and https://github.com/davidhalter/jedi-vim/issues/642, and caused by PR #640.

As with those, setting this in .vimrc seems to fix it:

`let g:jedi#call_signature_escape="'=`='"`

**Comment by kepbod** [comment] 2016-12-08 20:58
Same issue +1

**Comment by chris-johnson-tl** [comment] 2016-12-08 21:33
It appears that it might be some sort of regex thing, because '*' causes issues as well. The question is, @Aulddays, what characters need to be avoided to keep fixing this to revert your fix?

Is everyone happy with `,!,` or something?

**Comment by chppppp** [comment] 2016-12-08 21:58
> Seems to be related to #641 and #642, and caused by PR #640.
>As with those, setting this in .vimrc seems to fix it:
>let g:jedi#call_signature_escape="'=`='"
>Update: I've narrowed the problem down to the '?' character, trying to figure out why that breaks it before I submit a patch.

This does seem to fix it without breaking anything immediately noticeable :) Thanks

**Comment by blueyed** [comment] 2016-12-08 22:19
It looks like it is used in a regexp somehow, and there it is special.

**Comment by blueyed** [comment] 2016-12-08 22:23
See https://github.com/davidhalter/jedi-vim/blob/671f9f57804e9d47b50db3487fcb128eefc0db5d/jedi_vim.py#L338.

**Comment by blueyed** [comment] 2016-12-08 22:28
Duplicate of #641.
See https://github.com/davidhalter/jedi-vim/pull/646 for a fix.

**Closed by blueyed** 2016-12-08 22:28 UTC
