### ISSUE TITLE
jedi-vim\pythonx\jedi\jedi\evaluate\compiled\subprocess\__main__.py

### ISSUE THREAD

**Issue by kerwinxu** [davidhalter/jedi-vim#896] opened 2018-12-26 01:56 UTC
### Steps to reproduce
when I input "(" in new line , there is just "(" in new line  , gvim open file "E:\home\kerwin\vimfiles\pugged\jedi-vim\pythonx\jedi\jedi\evaluate\compiled\subprocess\__main__.py" in new window .

### Output of “:verbose JediDebugInfo”

Plug 'davidhalter/jedi-vim' , { 'for':['python']}
	autocmd FileType python set omnifunc=jedi#completions
	" let g:neocomplete#enable_auto_select = 1
	"let g:jedi#popup_select_first=1
	" set completeopt=longest,menuone
	" let g:jedi#auto_vim_configuration = 1
	" let g:jedi#popup_on_dot = 1
	if !exists('g:neocomplete#force_omni_input_patterns')
			let g:neocomplete#force_omni_input_patterns = {}
	endif
	let g:neocomplete#force_omni_input_patterns.python = '\%([^. \t]\.\|^\s*@\)\w*'
	let g:jedi#goto_command = "<leader>d"
	let g:jedi#goto_assignments_command = "<leader>g"
	" " let g:jedi#goto_definitions_command = ""
	let g:jedi#documentation_command = "<leader>k"
	" " let g:jedi#usages_command = "<leader>n"
	" " let g:jedi#completions_command = "<C-Space>"
	let g:jedi#rename_command = "<F2>"

**Comment by blueyed** [comment] 2018-12-26 04:31
Duplicate of https://github.com/davidhalter/jedi-vim/issues/870.

**Closed by blueyed** 2018-12-26 04:31 UTC
