### ISSUE TITLE
Vim's omni completion does not work from Windows and macOS from f9cbc65

### ISSUE THREAD

**Issue by kashewnuts** [davidhalter/jedi-vim#895] opened 2018-12-24 13:24 UTC
I came from jedi's Issue. https://github.com/davidhalter/jedi/issues/1266

## Problems summary

Omni completion does not work from Windows and mac from [f9cbc65](https://github.com/davidhalter/jedi/commit/f9cbc65f2d114d6252a1b42f9deb958d54ab7b95)

- Windows: [subprocess/__main__.py](https://github.com/davidhalter/jedi/blob/bd1010bbd2693f189ff780eb21fc4294071cb280/jedi/evaluate/compiled/subprocess/__main__.py) opens in a separate window, and "Pattern not found" occurs from `f9cbc65`.
- macOS: "Pattern not found" occurs from `f9cbc65`.

## Expected

Revert `f9cbc65` and Omni complementation will work in Vim.
I have confirmed that it will work with versions before `f9cbc65` and after reverting commit.

### Environment:

|OS|Vim Version|Python Version|
|--|-----------|--------------|
|Windows 10 PRo|[Vim8.1.0005](https://github.com/koron/vim-kaoriya/releases/download/v8.1.0005-20180520/vim81-kaoriya-win64-8.1.0005-20180520.zip)|[3.5.4](https://www.python.org/ftp/python/3.5.4/python-3.5.4-amd64.exe)|
|macOS Sierra| [macvim 8.0.1633](https://github.com/splhack/macvim-kaoriya/releases/download/20180324/MacVim-KaoriYa-20180324.dmg)|[3.6.4](https://www.python.org/ftp/python/3.6.4/python-3.6.4-macosx10.6.pkg)|

### Steps to reproduce

1. Prepare .vimrc below.

```vim
" .vimrc
call plug#begin('~/.cache/plugged')
Plug 'davidhalter/jedi-vim',          {'for': 'python'}
call plug#end()

let g:jedi#auto_initialization    = 0 " Disable the default initialization routine
let g:jedi#auto_vim_configuration = 0 " Don't change 'completeopt'
let g:jedi#popup_on_dot           = 0 " Manually press the completion key
let g:jedi#popup_select_first     = 0 " Don't select first completion entry
let g:jedi#show_call_signatures   = 0 " Avoid popups bugs
autocmd FileType python setlocal omnifunc=jedi#completions
```

2. Open Python file.
3. Vim's omni completion does not work

##### jedi-vim version

 - jedi-vim git version: 0.9.0-62-g7f4f2db
 - jedi git submodule status:  bd1010bbd2693f189ff780eb21fc4294071cb280 pythonx/jedi (v0.13.1)
 - parso git submodule status:  930ec08ab0cd77aae07e24aa78f9c5119be216bb pythonx/parso (v0.3.1-7-g93
0ec08)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28), [GCC 4.2.1 (Apple Inc. bui
ld 5666) (dot 3)]`
 - global site module: `/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py`

##### Jedi

 - path: `/Users/kashewnuts/.cache/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.13.1

##### Jedi environment: <SameEnvironment: 3.6.4 in /Library/Frameworks/Python.framework/Versions/3.6
>

 - executable: /Applications/MacVim.app/Contents/MacOS/Vim
ERROR: failed to get sys path from environment: jedi.api.environment.InvalidPythonEnvironment: Could
 not get version information for '/Applications/MacVim.app/Contents/MacOS/Vim': UnpicklingError("inv
alid load key, '\\x1b'.",)
  Traceback (most recent call last):
    File "/Users/kashewnuts/.cache/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 71, in display_
debug_info
      sys_path = environment.get_sys_path()
    File "/Users/kashewnuts/.cache/plugged/jedi-vim/pythonx/jedi/jedi/cache.py", line 143, in wrappe
r
      result = method(self, *args, **kwargs)
    File "/Users/kashewnuts/.cache/plugged/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 128,
 in get_sys_path
      return self._get_subprocess().get_sys_path()
    File "/Users/kashewnuts/.cache/plugged/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 79,
in _get_subprocess
      exc))

##### Settings

```
g:jedi#popup_select_first = 0 (default: 1)
g:jedi#auto_initialization = 0 (default: 1)
g:jedi#popup_on_dot = 0 (default: 1)
g:jedi#auto_vim_configuration = 0 (default: 1)

  omnifunc=jedi#completions
        最後にセットしたスクリプト: ~/.vimrc
  completeopt=menu,preview
```

**Comment by blueyed** [comment] 2018-12-26 04:31
Duplicate of https://github.com/davidhalter/jedi-vim/issues/870.

**Closed by blueyed** 2018-12-26 04:31 UTC

**Comment by kashewnuts** [comment] 2018-12-26 05:59
Thank you for triaging!

**Comment by zhanghang1989** [comment] 2019-02-05 17:07
Is this issue solved? I am still having the trouble.
