### ISSUE TITLE
Strange behavior: shell script appearing instead of autocomplete?

### ISSUE THREAD

**Issue by MikeDacre** [davidhalter/jedi-vim#384] opened 2015-04-13 00:30 UTC
In the following image:

![image](https://cloud.githubusercontent.com/assets/77714/7108363/99baf826-e138-11e4-84fb-cff7077959f2.png)

The line:  
    '=`=jedi=3, raise ValueError("File does not end in .sam, .sam.gz, or .bam")=`= (*_*value*_*, ..., sep = ' ', en'

Appears above the line I am editing when I use ``print(`` 

Here is a picture of the same file when I move the cursor somewhere else:

![image](https://cloud.githubusercontent.com/assets/77714/7108366/d14b7e5a-e138-11e4-9106-24e54d571a42.png)

I am using python 3.4, vim 7.4 (full compilation details below), and the following vim plugins:

    bufexplorer.zip                                                                                                                                                               
    gundo
    html5
    jedi
    nerdcommenter
    nerdtree
    perl-support
    riv
    screen
    sessionman
    snipmate
    syntastic
    taglist
    tasklist-pathogen
    vim-easy-align
    vim-fugitive
    vim-gnupg
    vim-indent-guides
    vim-latex-suite
    vim-matchit
    vim-multimarkdown
    vim-pandoc-syntax
    Vim-R-plugin
    vim-surround
    vim-table-mode
    vim-template
    vim-tmux-navigator
    vim_todo_highlight
    vimux

vim compilation details:

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 28 2015 09:06:53)
    Included patches: 1-663
    Compiled by Arch Linux
    Huge version without GUI.  Features included (+) or not (-):
    +acl             +farsi           +mouse_netterm   +syntax
    +arabic          +file_in_path    +mouse_sgr       +tag_binary
    +autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
    -balloon_eval    +float           +mouse_urxvt     -tag_any_white
    -browse          +folding         +mouse_xterm     -tcl
    ++builtin_terms  -footer          +multi_byte      +terminfo
    +byte_offset     +fork()          +multi_lang      +termresponse
    +cindent         +gettext         -mzscheme        +textobjects
    -clientserver    -hangul_input    +netbeans_intg   +title
    -clipboard       +iconv           +path_extra      -toolbar
    +cmdline_compl   +insert_expand   +perl            +user_commands
    +cmdline_hist    +jumplist        +persistent_undo +vertsplit
    +cmdline_info    +keymap          +postscript      +virtualedit
    +comments        +langmap         +printer         +visual
    +conceal         +libcall         +profile         +visualextra
    +cryptv          +linebreak       -python          +viminfo
    +cscope          +lispindent      +python3         +vreplace
    +cursorbind      +listcmds        +quickfix        +wildignore
    +cursorshape     +localmap        +reltime         +wildmenu
    +dialog_con      +lua             +rightleft       +windows
    +diff            +menu            +ruby            +writebackup
    +digraphs        +mksession       +scrollbind      -X11
    -dnd             +modify_fname    +signs           -xfontset
    -ebcdic          +mouse           +smartindent     -xim
    +emacs_tags      -mouseshape      -sniff           -xsmp
    +eval            +mouse_dec       +startuptime     -xterm_clipboard
    +ex_extra        +mouse_gpm       +statusline      -xterm_save
    +extra_search    -mouse_jsbterm   -sun_workshop    -xpm
      system vimrc file: "/etc/vimrc"
        user vimrc file: "$HOME/.vimrc"
    2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
      fall-back for $VIM: "/usr/share/vim"
    Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
    Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc  -L/usr/lib/python3.4/config-3.4m -lpython3.4m -lpthread -ldl -lutil -lm  -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib

**Comment by davidhalter** [comment] 2015-04-13 11:17
Can you reproduce that? If you restart VIM does it still happen? Because I cannot (VIM 7.3).

What commit of jedi-vim are you using? Something similar has been an issue, but I also fixed something a few days ago.

**Comment by MikeDacre** [comment] 2015-04-13 20:20
It is reproducible every time for me. I just tried again with the latest version from git.

It seems to happen every time I use the left parenthesis. e.g. plot.plot( or print(

I just tried completely deleting all other plugins, and using just my .vimrc, pathogen, and jedi and the problem is the same there.

My .vimrc is here: https://github.com/MikeDacre/.vim/blob/master/vimrc

**Comment by MikeDacre** [comment] 2015-04-13 20:34
Bingo, solved it. The error occurs when filetype is python3. Does jedi not support python3?

**Comment by davidhalter** [comment] 2015-04-13 20:51
jedi-vim does support python3 (or at least it should).

Hmm. So did you test it on a different machine? Because your VIM only supports python3.

**Comment by MikeDacre** [comment] 2015-04-13 20:54
Hi David,

Sorry to be unclear, it works fine with python3. They problem is with having the filetype set to python3.

Can you reproduce this on your machine?

In vim open a .py file, then type: ``:set filetype=python3`` go to a new line, and enter: ``print(``. Does everything work as expected?

I just changed my vimrc to get rid of python-mode and make the default filetype ``python`` instead of ``python3``, and now jedi is working fantastically (great job by the way, really amazing).

**Comment by davidhalter** [comment] 2015-04-13 22:09
I hve never heard of a python3 filetype. Is that a grammar file?

**Comment by MikeDacre** [comment] 2015-04-13 22:30
No, it is just a modification that a few people used to allow plugins to distinguish between python2 and python3 for the sake of syntax highlighting and formatting. It seems like it isn't needed anymore, everything is working great for me now, with this and with other python plugins, using filetype=python. A few years ago that was absolutely not the case.

My feeling from this conversation is that few people are using the python3 syntax filetype anymore, and everything is working fine for me now, so unless you want to try and make jedi work even for people who are using the python3 filetype, I am fine with closing the issue now. Thanks for all of your help.

**Comment by davidhalter** [comment] 2015-04-14 00:35
Yeah. I guess we're closing unless a lot of other people face this issue as well! :-)

Thanks for your investigations!

**Closed by davidhalter** 2015-04-14 00:35 UTC
Labels: not-reproducible
