### ISSUE TITLE
Call signature tooltip not dismissed

### ISSUE THREAD

**Issue by raptium** [davidhalter/jedi-vim#642] opened 2016-12-08 08:43 UTC
### Issue
Call signature tooltip is not dismissed when exit insert mode.
Magic strings are left in the file.

### Steps to reproduce
Type the following snippet into vim, wait until the signature tooltip `(a)` to appear, then press `ESC` and `:wq` to save and quit vim
```
def foo(a):
    pass

def bar(b):
    foo(
```

The tooltip is never dismissed and I get a corrupt py file with jedi magics `?!?jedi?!?`
```
def foo(a):
    pass

def ba?!?jedi=0, r(b):?!? (*_*a*_*) ?!?jedi?!?
    foo(
```

### Versions

 - jedi-vim: 671f9f57804e9d47b50db3487fcb128eefc0db5d  I think it's current master
 - Vim: 8.0.51 (Mac)
 - Python: 2.7.12

#561 was closed today, so I am creating a new issue here.

**Comment by davidhalter** [comment] 2016-12-08 09:02
I have just tried anI cannot reproduce it. What plugins are you using?

**Comment by raptium** [comment] 2016-12-08 09:11
Here goes my vundle settings:
```
Plugin 'gmarik/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'davidhalter/jedi-vim'
Plugin 'uarun/vim-protobuf'
Plugin 'nginx.vim'
```
and color schemes settings:
```
set background=dark
if $TERM == "xterm-256color"
    set t_Co=256
endif
colorscheme solarized
let g:solarized_termcolors=256
```

**Comment by raptium** [comment] 2016-12-08 09:33
The issue is gone after adding this to my vimrc
```
let g:jedi#call_signature_escape="'=`='"
```
This is equivalent to revert the last commit (671f9f5) in master.

**Comment by davidhalter** [comment] 2016-12-08 12:28
Can you remove solarized and retry (to see if that's the issue)?

**Comment by raptium** [comment] 2016-12-08 13:32
I've tried with solarized (and other plugins) removed, and the issue still remains.

I did some experiments on different `g:jedi#call_signature_escape` settings, like `!!@@!!` `??@@??`... The issue appears only when `call_signature_escape` is set to a string with a leading `?`.

**Comment by MadWombat** [comment] 2016-12-08 18:48
+1 happens to me too

:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  5 2016 11:50:46)
MacOS X (unix) version
Included patches: 1-106
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +cmdline_info    +eval            +iconv           +menu            +multi_byte      -python          +tag_binary      +vertsplit       -xpm
+arabic          +comments        +ex_extra        +insert_expand   +mksession       +multi_lang      +python3         +tag_old_static  +virtualedit     -xsmp
+autocmd         +conceal         +extra_search    +job             +modify_fname    -mzscheme        +quickfix        -tag_any_white   +visual          -xterm_clipboard
+balloon_eval    +cryptv          +farsi           +jumplist        +mouse           +netbeans_intg   +reltime         +tcl             +visualextra     -xterm_save
+browse          +cscope          +file_in_path    +keymap          +mouseshape      +num64           +rightleft       +termguicolors   +viminfo
++builtin_terms  +cursorbind      +find_in_path    +lambda          +mouse_dec       +odbeditor       +ruby            +terminfo        +vreplace
+byte_offset     +cursorshape     +float           +langmap         -mouse_gpm       +packages        +scrollbind      +termresponse    +wildignore
+channel         +dialog_con_gui  +folding         +libcall         -mouse_jsbterm   +path_extra      +signs           +textobjects     +wildmenu
+cindent         +diff            -footer          +linebreak       +mouse_netterm   +perl            +smartindent     +timers          +windows
+clientserver    +digraphs        +fork()          +lispindent      +mouse_sgr       +persistent_undo +startuptime     +title           +writebackup
+clipboard       +dnd             +fullscreen      +listcmds        -mouse_sysmouse  +postscript      +statusline      +toolbar         -X11
+cmdline_compl   -ebcdic          -gettext         +localmap        +mouse_urxvt     +printer         -sun_workshop    +transparency    -xfontset
+cmdline_hist    +emacs_tags      -hangul_input    -lua             +mouse_xterm     +profile         +syntax          +user_commands   +xim
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-prote
ctor  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m -lpython3.5m -
framework CoreFoundation -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby

**Comment by chris-johnson-tl** [comment] 2016-12-08 21:36
@raptium * will also cause it, not just ?. And I haven't tested + but that will probably break as well. Anything that the regex parser will try to interpret as attempting to repeat something that either doesn't exist or can't be repeated.

**Comment by blueyed** [comment] 2016-12-08 22:28
Duplicate of #641.
See https://github.com/davidhalter/jedi-vim/pull/646 for a fix.

**Closed by blueyed** 2016-12-08 22:28 UTC
