### ISSUE TITLE
Docstring doesn't show up when method declaration spans multiple lines

### ISSUE THREAD

**Issue by luislezcair** [davidhalter/jedi-vim#371] opened 2015-03-11 14:27 UTC
I found that the docstring window doesn't show the docstring when the method declaration it belongs to has more than one line. I tested with the following example:

I have a file MyClass.py

```python
class MyClass:
    def connect(self, arg1="default", arg2=3, arg4=True, someLongkeyword=1,
            extremelyLongKeywordArgument=""):
            """This is a test, this docstring doesn't show up in the docstring
            window beacause the method definition has multiple lines
            """
            print("connect method")
```
Then in a script:

```python
from MyClass import MyClass

if __name__ == '__main__':
    m = Myclass()
    # Here when I higlight the connect method in the completion popup, the doc window only
    # shows the method declaration, but not the docstring.
    m.connect()
```

If I change the method to a long single line the docstring appears just fine. That is:

```python
class MyClass:
    def connect(self, arg1="default", arg2=3, arg4=True, someLongkeyword=1, extremelyLongKeywordArgument=""):
            """This docstring appears in the window just fine, because the method 
            declaration is only one long line"""
            print("connect method")
```

**Comment by davidhalter** [comment] 2015-03-22 12:28
Jedi version? This might have been fixed in the latest master branch.

**Comment by luislezcair** [comment] 2015-03-22 13:50
Sorry, I forgot to mention that. I installed jedi-vim with Vundle so I have the latest version.

**Comment by davidhalter** [comment] 2015-03-23 11:53
Oh, I might have fixed something like that in the dev branch, could you try?

**Comment by luislezcair** [comment] 2015-03-23 13:47
I tried the dev branch and this bug is still present.

**Comment by davidhalter** [comment] 2015-03-23 23:29
Sorry, I cannot reproduce it. Tried quite a few things to reproduce it. Can you maybe play around with the Jedi API and see if it exists there? That would make reproduction easier I suppose.

I have a distinct feeling that I fixed a bug that looked a lot like this one a while ago. But at the same time, I'm not sure and this might be something else.

**Comment by luislezcair** [comment] 2015-03-24 04:50
After long hours I finally found the problem.

It turns out Vundle was downloading a custom version of Jedi along with jedi-vim as a git submodule, and vim was using that version, located in ~/.vim/bundles/jedi-vim/jedi instead of the system-wide version I installed with pip. That version was pointing to a commit from almost a year ago (tagged as release 0.8.0-final0).

So... I went to ~/.vim/bundle/jedi-vim/jedi and did `git checkout master`. Now this bug is gone.

I guess this is reproducible with a fresh install of jedi-vim. And may be it's time to update the submodule to point to a more recent version?

**Comment by davidhalter** [comment] 2015-03-24 09:49
Thanks! Well, I should update the jedi-vim version, but at the same time I want to do that when I'm releasing Jedi. I'm pretty sure that the commit you're talking about is the last released Jedi version. I'll try to release a new one soon, but until that point it will stay the same. (The pip version is also old btw).

**Closed by davidhalter** 2015-03-24 09:49 UTC
Labels: bug, not-reproducible
