### ISSUE TITLE
Rename is broken

### ISSUE THREAD

**Issue by dohsimpson** [davidhalter/jedi-vim#416] opened 2015-05-12 18:51 UTC
Here's the error message from vim:

1 change; before #2  1 seconds ago
1 change; before #1  2 seconds ago
Traceback (most recent call last):
  File "~/.vim/bundle/jedi-vim/jedi_vim.py", line 108, in wrapper
    return func(*args, **kwargs)
TypeError: goto() got an unexpected keyword argument 'is_related_name'
Traceback (most recent call last):
  File "~/.vim/bundle/jedi-vim/jedi_vim.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "~/.vim/bundle/jedi-vim/jedi_vim.py", line 456, in rename
    return do_rename(replace)
  File "~/.vim/bundle/jedi-vim/jedi_vim.py", line 481, in do_rename
    key=lambda x: (x.module_path, x.start_pos))
TypeError: 'NoneType' object is not iterable

**Comment by blueyed** [comment] 2015-05-12 20:11
Should be fixed by now (d79f4114).

I've also pushed a branch/PR with more chnages/fixes in this area: https://github.com/davidhalter/jedi-vim/pull/417

Would be nice, if you could provide feedback on that one.

Apart from that, I am closing this as fixed / duplicate of #414.

**Closed** 2015-05-12 20:17 UTC
