### ISSUE TITLE
Issues when working with splits

### ISSUE THREAD

**Issue by Plouff** [davidhalter/jedi-vim#322] opened 2014-11-04 14:23 UTC
Hello,

I am experiencing an annoying behavior when working with splits.
Usually I have multiple files open in the same tab in different splits.
The file I am working on has its split "maximized":
![image](https://cloud.githubusercontent.com/assets/977788/4900860/92a51500-642c-11e4-8e44-30f4cd8977da.png)

Now if I trigger a completion and select one item, then my splits are set to all equals when I leave insert mode.
That would lead to something like that:
![image](https://cloud.githubusercontent.com/assets/977788/4900902/eba60d9e-642c-11e4-95dd-712b6f285721.png)

Is there some kind of configuration regarding this behavior?
I read the doc but couldn't find anything...

Apart from that issue, I am pretty impressed by the capabilities of jedi-vim. I am learning PyQt, and the 3rd party lib is perfectly parsed. It makes me save so much time! It is just awesome!!!

Thank you for your help!

**Comment by littleq0903** [comment] 2015-02-07 11:14
I was interested by this bug, but I have not idea about reproducing this bug. (I use jedi-vim daily but never seen this bug)

Can you describe the step to reproduce this bug detailly? That would help, thanks.

(I was attracted because I am the author of goto's split function, I though it was my fault and run into here fast before I watched this issue's detail :P)

**Comment by nicolas33** [comment] 2015-11-04 08:49
This happens if the top window for signature and docstring opens. Steps to reproduce:
1. open a file.
2. `:split`
3. maximize lower window.
4. make completion happen with "top window", e.g. from blah import x
5. quit the insert mode with ESC. => split gets equalized.

**Comment by nicolas33** [comment] 2015-11-04 08:53
That's the `auto_close_doc` feature which is offending. ;-)

**Comment by littleq0903** [comment] 2015-11-04 10:44
okay, let me try.

**Comment by Aq32** [comment] 2020-10-28 12:23
> That's the `auto_close_doc` feature which is offending. ;-)

Using `:let g:jedi#auto_close_doc=0` does get rid of the buggy interface (by getting rid of the auto doc string) but is there a way to correct the buggy interface and still retain this feature? 

This isn't even that effective of a workaround since the auto doc can still reappear by pressing "Down" (selecting another autocomplete) anyway. Additionally using Ctrl+Space with a space or open bracket preceding the manual auto-complete keypress brings the auto doc back up again with the same bug.

(gVIM version 8.2)

**Comment by davidhalter** [comment] 2020-12-27 02:01
I'm not even sure what the issue here would be regarding jedi-vim. It's probably a general VIM issue (if it wasn't fixed). I'm closing, because I don't use and like splits and nobody else really stepped up and tried to improve stuff here.

**Closed by davidhalter** 2020-12-27 02:01 UTC
Labels: bug
