### ISSUE TITLE
Rename just work on the last variable

### ISSUE THREAD

**Issue by ladrift** [davidhalter/jedi-vim#414] opened 2015-05-09 15:34 UTC
example:
```python
foo = 1
b = foo
foo
```
when I use rename on the first `foo` and insert a new name(eg: boo), it will turn to this:
```python
foo = 1
b = foo
boo

**Comment by blueyed** [comment] 2015-05-09 16:28
Cannot reproduce it.

Are you using jedi-vim from Git master?
How do you invoke the renaming? Via the default mapping?
Does it work when you do `:call jedi#rename()` directly?

**Comment by blueyed** [comment] 2015-05-09 17:17
Also, which Python major version are you using?
I've just pushed a fix for saving/restoring the view in Python 2 (9a13f14).

**Comment by ladrift** [comment] 2015-05-10 00:16
I  use pip to pre-install jedi and Vundle to install jedi-vim by:
```vim
 Plugin 'davidhalter/jedi-vim'
```
I invoked it using `<leader>r`, the default mapping.
It produced the same outcome when i use `:call jedi#rename()`

I am using python3 on archlinux, using vim in Xfce4 Terminal

**Comment by davidhalter** [comment] 2015-05-10 01:31
Please update Jedi to the latest branch.

**Comment by ladrift** [comment] 2015-05-11 15:51
do you mean Jedi the python library?
I installed jedi library only for python3 and vim without python3 support
```
:ver

...
+python
-python3
```
Which version of python using by jedi-vim?

**Comment by davidhalter** [comment] 2015-05-11 19:41
Yes I mean the python library. Which version are you using?

**Comment by ladrift** [comment] 2015-05-12 14:46
```
% pip show jedi
---
Metadata-Version: 2.0
Name: jedi
Version: 0.9.0
Summary: An autocompletion tool for Python that can be used for text editors.
Home-page: https://github.com/davidhalter/jedi
Author: David Halter
Author-email: davidhalter88@gmail.com
License: MIT
Location: /usr/lib/python3.4/site-packages
Requires: 
```

**Comment by blueyed** [comment] 2015-05-12 14:53
@ladrift 
Have you tried latest master (after my comment about the fix I've pushed)?

Also, there might be something in Vim's `:mess`, e.g. a traceback from jedi-vim.

**Comment by ladrift** [comment] 2015-05-12 15:02
Really, there are traceback messages about jedi_vim.py
```
:mess
Traceback (most recent call last):
  File "/home/ladrift/.vim/bundle/jedi-vim/jedi_vim.py", line 107, in wrapper
    return func(*args, **kwargs)
  File "/home/ladrift/.vim/bundle/jedi-vim/jedi_vim.py", line 447, in rename
    return do_rename(replace)
  File "/home/ladrift/.vim/bundle/jedi-vim/jedi_vim.py", line 494, in do_rename
    vim_command('call winrestview(%s)' % PythonToVimStr(saved_view))
  File "/home/ladrift/.vim/bundle/jedi-vim/jedi_vim.py", line 30, in __new__
    return unicode.__new__(cls, obj, encoding)
TypeError: coercing to Unicode: need string or buffer, dict found
```
My jedi library on install for python3 is it a big deal or may the cause?

**Comment by blueyed** [comment] 2015-05-12 15:05
That's the issue I had fixed..!

Please update jedi-vim from Git master.

https://github.com/davidhalter/jedi-vim/commit/9a13f143a881d10b7aa86682d74ea82898f7e35e

**Comment by ladrift** [comment] 2015-05-12 16:14
thanks a lot

**Comment by blueyed** [comment] 2015-05-12 16:30
@ladrift 
You're welcome.  Glad it worked out! :)

It's OK to close the issue then.

**Comment by ladrift** [comment] 2015-05-12 16:33
T.T...Problem seems not solved. It turned to that renaming have no effect on any variable.
I use `git pull` to update
```
:mess
Traceback (most recent call last):
  File "/home/ladrift/.vim/bundle/jedi-vim/jedi_vim.py", line 108, in wrapper
    return func(*args, **kwargs)
TypeError: goto() got an unexpected keyword argument 'is_related_name'
Traceback (most recent call last):
  File "/home/ladrift/.vim/bundle/jedi-vim/jedi_vim.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "/home/ladrift/.vim/bundle/jedi-vim/jedi_vim.py", line 456, in rename
    return do_rename(replace)
  File "/home/ladrift/.vim/bundle/jedi-vim/jedi_vim.py", line 481, in do_rename
    key=lambda x: (x.module_path, x.start_pos))
TypeError: 'NoneType' object is not iterable
```

**Closed** 2015-05-12 17:43 UTC
Labels: bug, resolved

**Comment by blueyed** [comment] 2015-05-12 17:44
@ladrift 
Should be fixed in 651eac9.

I have some more fixes in this area, which I'll push later - maybe into a separate PR first.

Let me know if this works better now.

**Comment by blueyed** [comment] 2015-05-12 20:12
The PR is https://github.com/davidhalter/jedi-vim/pull/417.

Would be nice, if you could check this out and provide feedback.  It's (re)based on master.

**Comment by ladrift** [comment] 2015-05-13 05:04
@blueyed It works! Thanks for your great works.

**Comment by blueyed** [comment] 2015-05-13 08:44
Have you tried the PR?

**Comment by ladrift** [comment] 2015-05-13 21:48
@blueyed 
I just use `git pull` to update the jedi-vim.

**Comment by blueyed** [comment] 2015-05-14 01:39
Ok, I just wanted to make sure that the PR ould not break it somehow again.. ;)

I'll get it merged in the next days - IIRC David had reviewed it already.
