### ISSUE TITLE
Raises AttributeError: 'NoneType' object has no attribute 'goto_assignments'

### ISSUE THREAD

**Issue by anudeepsamaiya** [davidhalter/jedi-vim#894] opened 2018-12-20 10:41 UTC
### Issue
Jedi-vim does not jumps to definition.

### Steps to reproduce
press `<Leader>g`

### Output of “:verbose JediDebugInfo”
```
Traceback (most recent call last):
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 74, in _get_subprocess
    info = self._subprocess._send(None, _get_info)
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 242, in _send
    is_exception, traceback, result = pickle_load(self._process.stdout)
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi/jedi/_compatibility.py", line 464, in pickle_load
    return pickle.load(file, encoding='bytes')
_pickle.UnpicklingError: invalid load key, '\x1b'.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 220, in get_script
    environment=get_environment(),
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 108, in __init__
    project, environment=environment, script_path=self.path
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi/jedi/evaluate/__init__.py", line 94, in __init__
    self.compiled_subprocess = environment.get_evaluator_subprocess(self)
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 113, in get_evaluator_subprocess
    return EvaluatorSubprocess(evaluator, self._get_subprocess())
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 79, in _get_subprocess
    exc))
jedi.api.environment.InvalidPythonEnvironment: Could not get version information for '/usr/local/bin/vim': UnpicklingError("invalid load key, '\\x1b'.")
Traceback (most recent call last):
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/Users/anudeepsamaiya/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 306, in goto
    definitions = script.goto_assignments()
AttributeError: 'NoneType' object has no attribute 'goto_assignments'
```

**Comment by blueyed** [comment] 2018-12-20 17:11
> jedi.api.environment.InvalidPythonEnvironment: Could not get version information for '/usr/local/bin/vim': UnpicklingError("invalid load key, '\\x1b'.")

It tries to use `vim` as your Python there.

**Comment by anudeepsamaiya** [comment] 2018-12-21 07:44
> > jedi.api.environment.InvalidPythonEnvironment: Could not get version information for '/usr/local/bin/vim': UnpicklingError("invalid load key, '\x1b'.")
> 
> It tries to use `vim` as your Python there.

So what do you suggest, so that I can remedy this?

**Comment by blueyed** [comment] 2018-12-21 11:18
I am just giving pointers, no idea really.

It looks like `_pickle.UnpicklingError: invalid load key, '\x1b'.` might be caused by running vim instead of python in a subprocess.

It would be helpful if you filled in the issue template!
Also state if this started to happen only recently etc.

There are issues on Windows where vim is used instead of python (but for the main process IIRC), and some pickling issue (related to MacOS/Homebrew versions only?!, #889).

**Comment by hujianxin** [comment] 2018-12-23 08:49
Today I met a issue maybe the same as yours.

```
Traceback (most recent call last):
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 74, in _get_subprocess
    info = self._subprocess._send(None, _get_info)
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 242, in _send
    is_exception, traceback, result = pickle_load(self._process.stdout)
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi/jedi/_compatibility.py", line 464, in pickle_load
    return pickle.load(file, encoding='bytes')
_pickle.UnpicklingError: invalid load key, '3'.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 220, in get_script
    environment=get_environment(),
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 108, in __init__
    project, environment=environment, script_path=self.path
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/__init__.py", line 94, in __init__
    self.compiled_subprocess = environment.get_evaluator_subprocess(self)
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 113, in get_evaluator_subprocess
    return EvaluatorSubprocess(evaluator, self._get_subprocess())
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 79, in _get_subprocess
    exc))
jedi.api.environment.InvalidPythonEnvironment: Could not get version information for '/usr/local/Cellar/macvim/8.1-153/MacVim.app/Contents/bin/../MacOS/Vim': UnpicklingError("invalid load key, '3'.
")
Traceback (most recent call last):
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/Users/hujianxin/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 302, in goto
    definitions = script.goto_assignments(follow_imports=True)
AttributeError: 'NoneType' object has no attribute 'goto_assignments'
```

**Comment by hujianxin** [comment] 2018-12-23 08:52
1. this issue happen only recently
2. System: macos 10.14.1
3. python --version `Python 2.7.15`, I alse try pyenv global 3.7.0, failed too

**Comment by hujianxin** [comment] 2018-12-23 08:56
Maybe my issue is related to macvim...

**Comment by blueyed** [comment] 2018-12-26 04:41
Duplicate of #870.

**Closed by blueyed** 2018-12-26 04:41 UTC
Labels: need-information
