### ISSUE TITLE
Rename command not working

### ISSUE THREAD

**Issue by benbarbour** [davidhalter/jedi-vim#253] opened 2014-02-14 18:11 UTC
These are my current jedi settings:

```
let g:jedi#auto_vim_configuration = 0
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0
let g:jedi#use_tabs_not_buffers = 0
let g:jedi#use_splits_not_buffers = "bottom"
```

although I've also tried with `let g:jedi#auto_vim_configuration = 1` and without any of the `use_X_not_Y` options.

I hit `<leader>r` and it deletes the symbol under the cursor, and then drops me into insert mode. I type a new name, and press 'escape' to exit insert mode. Jedi then opens a new split (or a new tab if I don't have any of the use_X_not_Y lines set) that's viewing the same file except that no rename is done and both splits/tabs have lost syntax highlighting. The message bar prints "jedi did 1 renames!" Even if there were >1 instances of the symbol in the file.

**Comment by kjyv** [comment] 2016-03-15 09:48
Even though all other bugs relating to renaming are closed, the behavior for me is still pretty much like described in #126, it sometimes works fine and sometimes does not rename anything and sometimes also mangles the current symbol under the cursor instead. I don't get any windows opened.

**Comment by blueyed** [comment] 2016-03-16 23:12
@kjyv 
You would have to investigate (reproducible test case?).
I am not using this feature myself, although I have done some fixes for it.

**Comment by davidhalter** [comment] 2016-03-16 23:17
I'm not using this feature, neither (which is kind of sad, since I have programmed it). It's a long standing issue and we should really fix it, but I struggle to find the time.

**Comment by kjyv** [comment] 2016-04-03 17:41
It isn't really cleanly reproducible, it usually worked after a few tries and depends on position and word under the cursor. It's however possible that this was fixed in 0d613b5, I haven't had problems after it so far. I'll watch it for a bit and report back.

**Comment by cepedawitei** [comment] 2018-11-28 06:51
Same issue here. Here is my vim config

```
let g:jedi#popup_on_dot = 0
let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_definitions_command = "<leader>d"
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#rename_command = "<leader>r"
let g:jedi#show_call_signatures = "0"
let g:jedi#completions_command = "<C-Space>"
let g:jedi#smart_auto_mappings = 0
```

**Comment by davidhalter** [comment] 2019-12-22 18:02
It looks like the example above is working now. Please let me know about examples that are not working.

**Closed by davidhalter** 2019-12-22 18:02 UTC
Labels: bug, jedi-issue
