### ISSUE TITLE
Auto Completion not working with pipenv on msys2

### ISSUE THREAD

**Issue by adrianjord** [davidhalter/jedi-vim#853] opened 2018-07-23 05:04 UTC
### Issue

When installing a dependency with pipenv, jedi-vim does not autocomplete, however, saving does not throw any warnings.

### Steps to reproduce

Install msys2
Install vim
Install python 3.6
Install pipenv
Install jedi-vim via Vundle
Create new test dir
`pipenv install request`
Edit new file `main.py`
Type `import` then press `ctr+space`

Expected request to be in the list

#### Jedi-vim debug information

Using Python version: 3
 - global sys.version: `3.6.6 (default, Jun 28 2018, 10:27:26), [GCC 7.3.0]`
 - global site module: `/usr/lib/python3.6/site.py`
Jedi path: `/c/Users/adria/Documents/Home/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.12.1
 - environment: `<Environment: 3.6.6 in /usr>`
 - sys_path:
    - `/usr/lib/python36.zip`
    - `/usr/lib/python3.6`
    - `/usr/lib/python3.6/lib-dynload`
    - `/c/Users/adria/Documents/Home/.local/lib/python3.6/site-packages`
    - `/usr/lib/python3.6/site-packages`
 - jedi-vim git version: 0.9.0-31-g2bb7677
 - jedi git submodule status:  a79a1fbef57564d031c59f47def20a6d9adf3439 pythonx/jedi (v0.12.1)
 - parso git submodule status:  e6bc924fbabbfa3090044e475c91a7655b9c6e9b pythonx/parso (v0.3.1)

##### Settings
```
  omnifunc=jedi#completions
	Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim
  completeopt=menuone,longest,preview
	Last set from ~/.vim/bundle/jedi-vim/plugin/jedi.vim
```

#### :version
```

VIM - Vi IMproved 8.1 (2018 May 17, compiled May 31 2018 11:16:13)
Included patches: 1-22
Compiled by <alexpux@gmail.com>
Huge version without GUI.  Features included (+) or not (-):
+acl               +cryptv            -footer            +mksession         +path_extra        +syntax            +viminfo
+arabic            +cscope            +fork()            +modify_fname      +perl/dyn          +tag_binary        +vreplace
+autocmd           +cursorbind        +gettext           +mouse             +persistent_undo   +tag_old_static    +wildignore
-autoservername    +cursorshape       -hangul_input      -mouseshape        +postscript        -tag_any_white     +wildmenu
-balloon_eval      +dialog_con        +iconv             +mouse_dec         +printer           -tcl               +windows
+balloon_eval_term +diff              +insert_expand     -mouse_gpm         +profile           +termguicolors     +writebackup
-browse            +digraphs          +job               -mouse_jsbterm     +python/dyn        +terminal          -X11
++builtin_terms    -dnd               +jumplist          +mouse_netterm     +python3/dyn       +terminfo          -xfontset
+byte_offset       -ebcdic            +keymap            +mouse_sgr         +quickfix          +termresponse      -xim
+channel           +emacs_tags        +lambda            -mouse_sysmouse    +reltime           +textobjects       -xpm
+cindent           +eval              +langmap           +mouse_urxvt       +rightleft         +timers            -xsmp
-clientserver      +ex_extra          +libcall           +mouse_xterm       +ruby/dyn          +title             -xterm_clipboard
+clipboard         +extra_search      +linebreak         +multi_byte        +scrollbind        -toolbar           -xterm_save
+cmdline_compl     +farsi             +lispindent        +multi_lang        +signs             +user_commands     
+cmdline_hist      +file_in_path      +listcmds          -mzscheme          +smartindent       +vertsplit         
+cmdline_info      +find_in_path      +localmap          +netbeans_intg     +startuptime       +virtualedit       
+comments          +float             -lua               +num64             +statusline        +visual            
+conceal           +folding           +menu              +packages          -sun_workshop      +visualextra       
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim81"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -I/usr/include/ncursesw  -march=x86-64 -mtune=generic -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -pipe -fstack-protector -pipe -Wl,--as-needed -o vim.exe        -lm    -lncursesw -liconv -lacl -lintl   -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -ldl -lcrypt        
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"main.py" [unix] 5L, 126C

VIM - Vi IMproved 8.1 (2018 May 17, compiled May 31 2018 11:16:13)
  1: ~/.vimrc
  2: ~/.vim/user/defaults.vim
  3: /usr/share/vim/vim81/syntax/syntax.vim
  4: /usr/share/vim/vim81/syntax/synload.vim
  5: /usr/share/vim/vim81/syntax/syncolor.vim
  6: /usr/share/vim/vim81/filetype.vim
  7: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
  8: ~/.vim/user/vundle.vim
  9: /usr/share/vim/vim81/ftoff.vim
 10: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
 11: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
 12: ~/.vim/bundle/typescript-vim/ftdetect/typescript.vim
 13: ~/.vim/bundle/vim-prettier/ftdetect/css.vim
 14: ~/.vim/bundle/vim-prettier/ftdetect/graphql.vim
 15: ~/.vim/bundle/vim-prettier/ftdetect/javascript.vim
 16: ~/.vim/bundle/vim-prettier/ftdetect/json.vim
 17: ~/.vim/bundle/vim-prettier/ftdetect/less.vim
 18: ~/.vim/bundle/vim-prettier/ftdetect/markdown.vim
 19: ~/.vim/bundle/vim-prettier/ftdetect/scss.vim
 20: ~/.vim/bundle/vim-prettier/ftdetect/typescript.vim
 21: ~/.vim/bundle/vim-prettier/ftdetect/vue.vim
 22: /usr/share/vim/vim81/ftplugin.vim
 23: /usr/share/vim/vim81/indent.vim
 24: ~/.vim/bundle/spacemacs-theme.vim/colors/spacemacs-theme.vim
 25: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 26: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 27: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 28: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 29: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 30: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 31: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 32: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 33: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 34: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 35: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 36: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 37: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 38: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 39: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 40: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 41: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 42: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 43: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 44: ~/.vim/bundle/vim-devicons/nerdtree_plugin/webdevicons.vim
 45: ~/.vim/bundle/tagbar/plugin/tagbar.vim
 46: ~/.vim/bundle/BufOnly.vim/plugin/BufOnly.vim
 47: ~/.vim/bundle/vim-windowswap/plugin/WindowSwap.vim
 48: ~/.vim/bundle/ctrlp.vim/plugin/ctrlp.vim
 49: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/mrufiles.vim
 50: ~/.vim/bundle/neocomplete.vim/plugin/neocomplete/buffer.vim
 51: ~/.vim/bundle/neocomplete.vim/plugin/neocomplete/dictionary.vim
 52: ~/.vim/bundle/neocomplete.vim/plugin/neocomplete/member.vim
 53: ~/.vim/bundle/neocomplete.vim/plugin/neocomplete/tag.vim
 54: ~/.vim/bundle/neocomplete.vim/plugin/neocomplete.vim
 55: ~/.vim/bundle/vim-buffergator/plugin/buffergator.vim
 56: ~/.vim/bundle/searchtasks.vim/plugin/searchtasks.vim
 57: ~/.vim/bundle/vim-dispatch/plugin/dispatch.vim
 58: ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim
 59: ~/.vim/bundle/syntastic/plugin/syntastic/autoloclist.vim
 60: ~/.vim/bundle/syntastic/plugin/syntastic/balloons.vim
 61: ~/.vim/bundle/syntastic/plugin/syntastic/checker.vim
 62: ~/.vim/bundle/syntastic/plugin/syntastic/cursor.vim
 63: ~/.vim/bundle/syntastic/plugin/syntastic/highlighting.vim
 64: ~/.vim/bundle/syntastic/plugin/syntastic/loclist.vim
 65: ~/.vim/bundle/syntastic/plugin/syntastic/modemap.vim
 66: ~/.vim/bundle/syntastic/plugin/syntastic/notifiers.vim
 67: ~/.vim/bundle/syntastic/plugin/syntastic/registry.vim
 68: ~/.vim/bundle/syntastic/plugin/syntastic/signs.vim
 69: ~/.vim/bundle/syntastic/plugin/syntastic.vim
 70: ~/.vim/bundle/syntastic/autoload/syntastic/util.vim
 71: ~/.vim/bundle/vim-prettier/plugin/prettier.vim
 72: ~/.vim/bundle/omnisharp-vim/plugin/OmniSharp.vim
 73: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 74: ~/.vim/bundle/AnsiEsc.vim/plugin/AnsiEscPlugin.vim
 75: ~/.vim/bundle/AnsiEsc.vim/plugin/cecutil.vim
 76: ~/.vim/bundle/vim-devicons/plugin/webdevicons.vim
 77: ~/.vim/bundle/vim-airline/plugin/airline.vim
 78: ~/.vim/bundle/vim-airline/autoload/airline/init.vim
 79: ~/.vim/bundle/vim-airline/autoload/airline/parts.vim
 80: ~/.vim/bundle/vim-airline-themes/plugin/airline-themes.vim
 81: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
 82: /usr/share/vim/vim81/plugin/gzip.vim
 83: /usr/share/vim/vim81/plugin/logiPat.vim
 84: /usr/share/vim/vim81/plugin/manpager.vim
 85: /usr/share/vim/vim81/plugin/matchparen.vim
 86: /usr/share/vim/vim81/plugin/netrwPlugin.vim
 87: /usr/share/vim/vim81/plugin/rrhelper.vim
 88: /usr/share/vim/vim81/plugin/spellfile.vim
 89: /usr/share/vim/vim81/plugin/tarPlugin.vim
 90: /usr/share/vim/vim81/plugin/tohtml.vim
 91: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 92: /usr/share/vim/vim81/plugin/zipPlugin.vim
 93: ~/.vim/bundle/indentLine/after/plugin/indentLine.vim
 94: /usr/share/vim/vim81/syntax/python.vim
 95: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 96: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 97: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 98: /usr/share/vim/vim81/ftplugin/python.vim
 99: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
100: /usr/share/vim/vim81/indent/python.vim
101: ~/.vim/bundle/vim-airline/autoload/airline/extensions.vim
102: ~/.vim/bundle/vim-airline/autoload/airline/extensions/quickfix.vim
103: ~/.vim/bundle/vim-airline/autoload/airline.vim
104: ~/.vim/bundle/vim-airline/autoload/airline/extensions/netrw.vim
105: ~/.vim/bundle/vim-airline/autoload/airline/extensions/term.vim
106: ~/.vim/bundle/vim-airline/autoload/airline/extensions/ctrlp.vim
107: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tagbar.vim
108: ~/.vim/bundle/vim-airline/autoload/airline/util.vim
109: ~/.vim/bundle/vim-airline/autoload/airline/extensions/branch.vim
110: ~/.vim/bundle/vim-airline/autoload/airline/extensions/fugitiveline.vim
111: ~/.vim/bundle/vim-airline/autoload/airline/extensions/syntastic.vim
112: ~/.vim/bundle/vim-airline/autoload/airline/extensions/whitespace.vim
113: ~/.vim/bundle/vim-airline/autoload/airline/extensions/po.vim
114: ~/.vim/bundle/vim-airline/autoload/airline/extensions/wordcount.vim
115: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline.vim
116: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/autoshow.vim
117: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/tabs.vim
118: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buffers.vim
119: ~/.vim/bundle/vim-airline/autoload/airline/extensions/keymap.vim
120: ~/.vim/bundle/vim-airline/autoload/airline/extensions/windowswap.vim
121: ~/.vim/bundle/vim-airline/autoload/airline/section.vim
122: ~/.vim/bundle/vim-airline/autoload/airline/highlighter.vim
123: ~/.vim/bundle/vim-airline-themes/autoload/airline/themes/base16.vim
124: ~/.vim/bundle/vim-airline/autoload/airline/themes.vim
125: ~/.vim/bundle/vim-airline/autoload/airline/builder.vim
126: ~/.vim/bundle/vim-airline/autoload/airline/extensions/default.vim
127: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/utils.vim
128: ~/.vim/bundle/syntastic/autoload/syntastic/log.vim
129: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/ctrlspace.vim
130: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/builder.vim
131: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buflist.vim
132: ~/.vim/bundle/vim-devicons/autoload/airline/extensions/tabline/formatters/webdevicons.vim
133: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/formatters/default.vim
134: ~/.vim/bundle/vim-airline/autoload/airline/async.vim
135: ~/.vim/bundle/vim-fugitive/autoload/fugitive.vim
136: ~/.vim/bundle/tagbar/autoload/tagbar.vim
137: ~/.vim/bundle/tagbar/autoload/tagbar/debug.vim
138: ~/.vim/bundle/vim-windowswap/autoload/WindowSwap.vim
```

<details><summary>:scriptnames</summary>

```
  1: ~/.vimrc
  2: ~/.vim/user/defaults.vim
  3: /usr/share/vim/vim81/syntax/syntax.vim
  4: /usr/share/vim/vim81/syntax/synload.vim
  5: /usr/share/vim/vim81/syntax/syncolor.vim
  6: /usr/share/vim/vim81/filetype.vim
  7: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
  8: ~/.vim/user/vundle.vim
  9: /usr/share/vim/vim81/ftoff.vim
 10: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
 11: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
 12: ~/.vim/bundle/typescript-vim/ftdetect/typescript.vim
 13: ~/.vim/bundle/vim-prettier/ftdetect/css.vim
 14: ~/.vim/bundle/vim-prettier/ftdetect/graphql.vim
 15: ~/.vim/bundle/vim-prettier/ftdetect/javascript.vim
 16: ~/.vim/bundle/vim-prettier/ftdetect/json.vim
 17: ~/.vim/bundle/vim-prettier/ftdetect/less.vim
 18: ~/.vim/bundle/vim-prettier/ftdetect/markdown.vim
 19: ~/.vim/bundle/vim-prettier/ftdetect/scss.vim
 20: ~/.vim/bundle/vim-prettier/ftdetect/typescript.vim
 21: ~/.vim/bundle/vim-prettier/ftdetect/vue.vim
 22: /usr/share/vim/vim81/ftplugin.vim
 23: /usr/share/vim/vim81/indent.vim
 24: ~/.vim/bundle/spacemacs-theme.vim/colors/spacemacs-theme.vim
 25: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 26: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 27: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 28: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 29: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 30: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 31: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 32: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 33: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 34: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 35: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 36: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 37: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 38: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 39: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 40: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 41: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 42: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 43: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 44: ~/.vim/bundle/vim-devicons/nerdtree_plugin/webdevicons.vim
 45: ~/.vim/bundle/tagbar/plugin/tagbar.vim
 46: ~/.vim/bundle/BufOnly.vim/plugin/BufOnly.vim
 47: ~/.vim/bundle/vim-windowswap/plugin/WindowSwap.vim
 48: ~/.vim/bundle/ctrlp.vim/plugin/ctrlp.vim
 49: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/mrufiles.vim
 50: ~/.vim/bundle/neocomplete.vim/plugin/neocomplete/buffer.vim
 51: ~/.vim/bundle/neocomplete.vim/plugin/neocomplete/dictionary.vim
 52: ~/.vim/bundle/neocomplete.vim/plugin/neocomplete/member.vim
 53: ~/.vim/bundle/neocomplete.vim/plugin/neocomplete/tag.vim
 54: ~/.vim/bundle/neocomplete.vim/plugin/neocomplete.vim
 55: ~/.vim/bundle/vim-buffergator/plugin/buffergator.vim
 56: ~/.vim/bundle/searchtasks.vim/plugin/searchtasks.vim
 57: ~/.vim/bundle/vim-dispatch/plugin/dispatch.vim
 58: ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim
 59: ~/.vim/bundle/syntastic/plugin/syntastic/autoloclist.vim
 60: ~/.vim/bundle/syntastic/plugin/syntastic/balloons.vim
 61: ~/.vim/bundle/syntastic/plugin/syntastic/checker.vim
 62: ~/.vim/bundle/syntastic/plugin/syntastic/cursor.vim
 63: ~/.vim/bundle/syntastic/plugin/syntastic/highlighting.vim
 64: ~/.vim/bundle/syntastic/plugin/syntastic/loclist.vim
 65: ~/.vim/bundle/syntastic/plugin/syntastic/modemap.vim
 66: ~/.vim/bundle/syntastic/plugin/syntastic/notifiers.vim
 67: ~/.vim/bundle/syntastic/plugin/syntastic/registry.vim
 68: ~/.vim/bundle/syntastic/plugin/syntastic/signs.vim
 69: ~/.vim/bundle/syntastic/plugin/syntastic.vim
 70: ~/.vim/bundle/syntastic/autoload/syntastic/util.vim
 71: ~/.vim/bundle/vim-prettier/plugin/prettier.vim
 72: ~/.vim/bundle/omnisharp-vim/plugin/OmniSharp.vim
 73: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 74: ~/.vim/bundle/AnsiEsc.vim/plugin/AnsiEscPlugin.vim
 75: ~/.vim/bundle/AnsiEsc.vim/plugin/cecutil.vim
 76: ~/.vim/bundle/vim-devicons/plugin/webdevicons.vim
 77: ~/.vim/bundle/vim-airline/plugin/airline.vim
 78: ~/.vim/bundle/vim-airline/autoload/airline/init.vim
 79: ~/.vim/bundle/vim-airline/autoload/airline/parts.vim
 80: ~/.vim/bundle/vim-airline-themes/plugin/airline-themes.vim
 81: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
 82: /usr/share/vim/vim81/plugin/gzip.vim
 83: /usr/share/vim/vim81/plugin/logiPat.vim
 84: /usr/share/vim/vim81/plugin/manpager.vim
 85: /usr/share/vim/vim81/plugin/matchparen.vim
 86: /usr/share/vim/vim81/plugin/netrwPlugin.vim
 87: /usr/share/vim/vim81/plugin/rrhelper.vim
 88: /usr/share/vim/vim81/plugin/spellfile.vim
 89: /usr/share/vim/vim81/plugin/tarPlugin.vim
 90: /usr/share/vim/vim81/plugin/tohtml.vim
 91: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 92: /usr/share/vim/vim81/plugin/zipPlugin.vim
 93: ~/.vim/bundle/indentLine/after/plugin/indentLine.vim
 94: /usr/share/vim/vim81/syntax/python.vim
 95: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 96: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 97: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 98: /usr/share/vim/vim81/ftplugin/python.vim
 99: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
100: /usr/share/vim/vim81/indent/python.vim
101: ~/.vim/bundle/vim-airline/autoload/airline/extensions.vim
102: ~/.vim/bundle/vim-airline/autoload/airline/extensions/quickfix.vim
103: ~/.vim/bundle/vim-airline/autoload/airline.vim
104: ~/.vim/bundle/vim-airline/autoload/airline/extensions/netrw.vim
105: ~/.vim/bundle/vim-airline/autoload/airline/extensions/term.vim
106: ~/.vim/bundle/vim-airline/autoload/airline/extensions/ctrlp.vim
107: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tagbar.vim
108: ~/.vim/bundle/vim-airline/autoload/airline/util.vim
109: ~/.vim/bundle/vim-airline/autoload/airline/extensions/branch.vim
110: ~/.vim/bundle/vim-airline/autoload/airline/extensions/fugitiveline.vim
111: ~/.vim/bundle/vim-airline/autoload/airline/extensions/syntastic.vim
112: ~/.vim/bundle/vim-airline/autoload/airline/extensions/whitespace.vim
113: ~/.vim/bundle/vim-airline/autoload/airline/extensions/po.vim
114: ~/.vim/bundle/vim-airline/autoload/airline/extensions/wordcount.vim
115: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline.vim
116: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/autoshow.vim
117: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/tabs.vim
118: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buffers.vim
119: ~/.vim/bundle/vim-airline/autoload/airline/extensions/keymap.vim
120: ~/.vim/bundle/vim-airline/autoload/airline/extensions/windowswap.vim
121: ~/.vim/bundle/vim-airline/autoload/airline/section.vim
122: ~/.vim/bundle/vim-airline/autoload/airline/highlighter.vim
123: ~/.vim/bundle/vim-airline-themes/autoload/airline/themes/base16.vim
124: ~/.vim/bundle/vim-airline/autoload/airline/themes.vim
125: ~/.vim/bundle/vim-airline/autoload/airline/builder.vim
126: ~/.vim/bundle/vim-airline/autoload/airline/extensions/default.vim
127: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/utils.vim
128: ~/.vim/bundle/syntastic/autoload/syntastic/log.vim
129: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/ctrlspace.vim
130: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/builder.vim
131: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buflist.vim
132: ~/.vim/bundle/vim-devicons/autoload/airline/extensions/tabline/formatters/webdevicons.vim
133: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/formatters/default.vim
134: ~/.vim/bundle/vim-airline/autoload/airline/async.vim
135: ~/.vim/bundle/vim-fugitive/autoload/fugitive.vim
136: ~/.vim/bundle/tagbar/autoload/tagbar.vim
137: ~/.vim/bundle/tagbar/autoload/tagbar/debug.vim
138: ~/.vim/bundle/vim-windowswap/autoload/WindowSwap.vim
```
</details>

**Comment by davidhalter** [comment] 2018-07-23 06:57
I have no idea how pipenv actually works (especially not on Windows, I'm not even using it on Linux), I think the problem is that either the `VIRTUAL_ENV` variable is not defined when using pipenv or you're starting VIM before "activating" the virtualenv.

I think that https://github.com/davidhalter/jedi-vim/pull/836 will definitely help you as soon as it's merged. We're just not finished with that, yet. 

Our problem is that it's pretty hard to find the right Python version to execute. We look for a virtualenv and then the latest (3.6, 3.7 is not supported yet). For everything else we still have to write some code so users can select Python environments themselves.

**Comment by blueyed** [comment] 2018-07-23 07:09
Try `pipenv shell` before running Vim therein.
Then check if the "environment" in `:JediDebugInfo` reflects that - currently it is "environment: <Environment: 3.6.6 in /usr>" for you.

**Closed** 2018-07-23 18:18 UTC

**Comment by blueyed** [comment] 2018-07-24 00:04
@adrianjord 
Just find the `python` binary you need and add it to `$PATH`/`%PATH%` I guess.
Try `which python` after `pipenv shell`.

**Comment by blueyed** [comment] 2018-07-24 06:42
Typically pipenv creates a virtualenv in `.venv` (just like `python -m venv .venv`).
Anyway, not the right place anymore for support I guess.. :)
