### ISSUE TITLE
Completeion not working with parenthesises

### ISSUE THREAD

**Issue by shiny-comic** [davidhalter/jedi-vim#913] opened 2019-02-26 14:31 UTC
### Issue

Hi.
When I try to do completion with the code below, the popup come out.
![no-parenthesis](https://user-images.githubusercontent.com/7454810/53419341-08f13980-3a1d-11e9-9ec5-adc6f16b7cb5.png)

But when I add parenthesises as shown below,
![with-parenthesis](https://user-images.githubusercontent.com/7454810/53419356-14dcfb80-3a1d-11e9-80b5-36e28df19f00.png)
nothing come out.

In IPython, I can get the list of completion with jedi.
![in-ipython](https://user-images.githubusercontent.com/7454810/53418951-3984a380-3a1c-11e9-8301-7da63bf05d65.png)

Also I can get completion with `set omnifunc=python3complete#Complete`.
![using-python3complete](https://user-images.githubusercontent.com/7454810/53420176-9b460d00-3a1e-11e9-8959-9fc80aee85e0.png)

The minimum vimrc I used to check is this.
```
filetype off
filetype plugin indent off
scriptencoding utf-8

let s:vimplug_path = '~/test/autoload/plug.vim'
if !filereadable(s:vimplug_path)
  silent execute '!curl -fLo ' . s:vimplug_path . ' --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif
call plug#begin('~/test/plugged')
  Plug 'davidhalter/jedi-vim', {'for': 'python'}
call plug#end()

set background=dark
colorscheme desert
```

##### jedi-vim version

 - jedi-vim git version: ea5e87a
 - jedi git submodule status:  bd1010bbd2693f189ff780eb21fc4294071cb280 pythonx/jedi (v0.13.1)
 - parso git submodule status:  f1ee7614c921e538aa093cd96c78e9aaced7a8ca pythonx/parso (v0.3.3)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.7.2 (default, Feb 12 2019, 08:15:36), [Clang 10.0.0 (clang-1000.11.45.5)]`
 - global site module: `/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py`

##### Jedi

 - path: `/Users/shiny-comic/test/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.13.1

##### Jedi environment: <SameEnvironment: 3.7.2 in /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7>

 - executable: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/bin/python3
 - sys_path:
    - `/usr/local/lib/python3.7/site-packages/_pdbpp_path_hack`
    - `/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python37.zip`
    - `/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7`
    - `/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload`
    - `/usr/local/lib/python3.7/site-packages`

##### Known environments

 - <Environment: 3.7.2 in /usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7> (/usr/local/opt/python/bin/python3.7)

 - <Environment: 2.7.10 in /System/Library/Frameworks/Python.framework/Versions/2.7> (/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python)

##### Settings

```
  omnifunc=jedi#completions
	Last set from ~/dotfiles/.vim/after/ftplugin/python.vim line 18
  completeopt=menuone,longest,preview
	Last set from ~/test/plugged/jedi-vim/plugin/jedi.vim line 31
```

#### :version
```

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)
macOS version
Included patches: 1-950
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
+autochdir         +float             +mouse_xterm       +terminal
-autoservername    +folding           +multi_byte        +terminfo
+balloon_eval      -footer            +multi_lang        +termresponse
+balloon_eval_term +fork()            -mzscheme          +textobjects
+browse            +fullscreen        +netbeans_intg     +textprop
++builtin_terms    -gettext           +num64             +timers
+byte_offset       -hangul_input      +odbeditor         +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +transparency
+clientserver      +job               +perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              -mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -L.  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -framework Ruby    
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"../stest.py" 5L, 84C

```

<details><summary>:scriptnames</summary>

```
  1: ~/dotfiles/minivimrc
  2: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/ftoff.vim
  3: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/ftplugof.vim
  4: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/indoff.vim
  5: ~/dotfiles/.vim/autoload/plug.vim
  6: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/filetype.vim
  7: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/ftplugin.vim
  8: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/indent.vim
  9: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/syntax/syntax.vim
 10: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/syntax/synload.vim
 11: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/syntax/syncolor.vim
 12: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/defaults.vim
 13: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/syntax/nosyntax.vim
 14: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/colors/desert.vim
 15: ~/dotfiles/.vim/plugin/myfunc.vim
 16: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/getscriptPlugin.vim
 17: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/gzip.vim
 18: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/logiPat.vim
 19: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/manpager.vim
 20: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/matchparen.vim
 21: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/netrwPlugin.vim
 22: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/rrhelper.vim
 23: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/spellfile.vim
 24: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/tarPlugin.vim
 25: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/tohtml.vim
 26: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/vimballPlugin.vim
 27: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/plugin/zipPlugin.vim
 28: ~/dotfiles/.vim/after/plugin/common_settings.vim
 29: ~/test/plugged/jedi-vim/plugin/jedi.vim
 30: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/syntax/python.vim
 31: ~/test/plugged/jedi-vim/after/syntax/python.vim
 32: ~/test/plugged/jedi-vim/autoload/jedi.vim
 33: ~/test/plugged/jedi-vim/ftplugin/python/jedi.vim
 34: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/ftplugin/python.vim
 35: ~/test/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 36: ~/dotfiles/.vim/after/ftplugin/python.vim
 37: /usr/local/Cellar/macvim/8.1-155/MacVim.app/Contents/Resources/vim/runtime/indent/python.vim
 38: ~/dotfiles/.vim/after/syntax/python.vim
```
</details>

**Comment by davidhalter** [comment] 2019-02-27 19:57
This is probably not really fixable. The problem is that `python3complete#Complete` just imports the library and uses dir on it. This obviously leads to almost perfect completions, but it's really dangerous.

Same for IPython, you have the runtime object already (because you imported it previously - so it's not dangerous, because you did it yourself).

So it's just not really the same.

Where is PyQT installed?

**Comment by davidhalter** [comment] 2019-02-27 20:00
Might be related to https://github.com/davidhalter/jedi-vim/issues/913

**Comment by davidhalter** [comment] 2019-02-27 20:10
In #913 a similar question was asked. I think that PyQT5 completions just won't really work. I'm closing in favor of that issue. Please subscribe there.

Until this has been fixed, adding `PyQT5` to `jedi.settings.auto_import_modules might help. Not sure if it does.

**Closed by davidhalter** 2019-02-27 20:10 UTC
