### ISSUE TITLE
jedi-vim showing =`=jedi= ... =`=jedi`=`

### ISSUE THREAD

**Issue by strin** [davidhalter/jedi-vim#528] opened 2016-01-14 23:18 UTC
Normally it should show hints like arglists for f(arglist), 
but sometimes it shows weird  =`=jedi= (arglist) =`=jedi`=`.

**Comment by blueyed** [comment] 2016-01-15 14:22
See also #515.

Can you provide a test case to reproduce it?

**Comment by davidhalter** [comment] 2016-01-16 09:51
Closing because it's a duplicate. However, please comment if you can reproduce it with a test case.

**Closed by davidhalter** 2016-01-16 09:51 UTC

**Comment by strin** [comment] 2016-01-18 20:02
issue solved. jedi-vim seems to have a conflict with my syntax file.
i am using the syntax from pymode.
