### ISSUE TITLE
For method compeletion the first method now automatically prints.

### ISSUE THREAD

**Issue by moorepants** [davidhalter/jedi-vim#400] opened 2015-05-01 01:04 UTC
I upgraded jedi-vim today with vundle and now get different behavior in method completion.

Previously, if I have an object and type `.` a list of optional methods appear, which I can choose from or just continue typing.

Now when I type `.` the first method in the list is automatically completed and I have to delete that method to type the one I want.

**Comment by blueyed** [comment] 2015-05-01 01:40
What does `:set completeopt?` give you?
What jedi-vim config do you have?
Are you using other completion plugins / settings?

**Comment by moorepants** [comment] 2015-05-01 01:43
> What does `:set completeopt?` give you?

`completeopt=menuone,longest,preview`

>  What jedi-vim config do you have?

https://github.com/moorepants/dotfiles/blob/master/vimrc

>  Are you using other completion plugins / settings?
```
Plugin 'gmarik/vundle'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'klen/python-mode'
Plugin 'davidhalter/jedi-vim'
Plugin 'vim-scripts/taglist.vim'
Plugin 'vim-scripts/ToggleComment'
Plugin 'git://git.code.sf.net/p/vim-latex/vim-latex'
```

**Comment by blueyed** [comment] 2015-05-01 02:43
It's a duplicate of #399, and I think I have a fix for that regression.

**Closed by blueyed** 2015-05-01 02:43 UTC
